
export const POPULAR_STOCKS = [
  // --- MAGNIFICENT 7 & MEGA CAP ---
  { symbol: 'NVDA', name: 'NVIDIA', sector: 'Technology' },
  { symbol: 'MSFT', name: 'Microsoft', sector: 'Technology' },
  { symbol: 'AAPL', name: 'Apple', sector: 'Technology' },
  { symbol: 'GOOGL', name: 'Alphabet A', sector: 'Technology' },
  { symbol: 'GOOG', name: 'Alphabet C', sector: 'Technology' },
  { symbol: 'AMZN', name: 'Amazon', sector: 'Consumer Cyclical' },
  { symbol: 'META', name: 'Meta Platforms', sector: 'Communication' },
  { symbol: 'TSLA', name: 'Tesla', sector: 'Consumer Cyclical' },
  { symbol: 'AVGO', name: 'Broadcom', sector: 'Technology' },
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Healthcare' },
  { symbol: 'BRK/B', name: 'Berkshire Hathaway', sector: 'Financial' },
  { symbol: 'V', name: 'Visa', sector: 'Financial' },
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Financial' },
  { symbol: 'WMT', name: 'Walmart', sector: 'Consumer Defensive' },
  { symbol: 'XOM', name: 'Exxon Mobil', sector: 'Energy' },
  { symbol: 'MA', name: 'Mastercard', sector: 'Financial' },
  { symbol: 'UNH', name: 'UnitedHealth', sector: 'Healthcare' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer Defensive' },
  { symbol: 'COST', name: 'Costco', sector: 'Consumer Defensive' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'ABBV', name: 'AbbVie', sector: 'Healthcare' },
  { symbol: 'ORCL', name: 'Oracle', sector: 'Technology' },
  { symbol: 'HD', name: 'Home Depot', sector: 'Consumer Cyclical' },
  { symbol: 'MRK', name: 'Merck', sector: 'Healthcare' },
  { symbol: 'CVX', name: 'Chevron', sector: 'Energy' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Financial' },
  { symbol: 'CRM', name: 'Salesforce', sector: 'Technology' },
  { symbol: 'NFLX', name: 'Netflix', sector: 'Communication' },
  { symbol: 'KO', name: 'Coca-Cola', sector: 'Consumer Defensive' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Consumer Defensive' },
  { symbol: 'TMO', name: 'Thermo Fisher', sector: 'Healthcare' },
  { symbol: 'LIN', name: 'Linde', sector: 'Materials' },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Financial' },
  { symbol: 'AMD', name: 'AMD', sector: 'Technology' },
  { symbol: 'ADBE', name: 'Adobe', sector: 'Technology' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Technology' },
  { symbol: 'CSCO', name: 'Cisco', sector: 'Technology' },
  { symbol: 'DIS', name: 'Walt Disney', sector: 'Communication' },
  { symbol: 'ABT', name: 'Abbott Labs', sector: 'Healthcare' },
  { symbol: 'TMUS', name: 'T-Mobile', sector: 'Communication' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrials' },
  { symbol: 'INTC', name: 'Intel', sector: 'Technology' },
  { symbol: 'INTU', name: 'Intuit', sector: 'Technology' },
  { symbol: 'CAT', name: 'Caterpillar', sector: 'Industrials' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Communication' },
  { symbol: 'CMCSA', name: 'Comcast', sector: 'Communication' },
  { symbol: 'DHR', name: 'Danaher', sector: 'Healthcare' },
  { symbol: 'IBM', name: 'IBM', sector: 'Technology' },
  { symbol: 'NOW', name: 'ServiceNow', sector: 'Technology' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
  { symbol: 'UBER', name: 'Uber', sector: 'Technology' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Healthcare' },
  { symbol: 'PM', name: 'Philip Morris', sector: 'Consumer Defensive' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare' },
  { symbol: 'SPGI', name: 'S&P Global', sector: 'Financial' },
  { symbol: 'HON', name: 'Honeywell', sector: 'Industrials' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'UNP', name: 'Union Pacific', sector: 'Industrials' },
  { symbol: 'AXP', name: 'American Express', sector: 'Financial' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Financial' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financial' },
  { symbol: 'RTX', name: 'RTX Corp', sector: 'Industrials' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrials' },
  { symbol: 'SYK', name: 'Stryker', sector: 'Healthcare' },
  { symbol: 'BLK', name: 'BlackRock', sector: 'Financial' },
  { symbol: 'LOW', name: 'Lowes', sector: 'Consumer Cyclical' },
  { symbol: 'ELV', name: 'Elevance Health', sector: 'Healthcare' },
  { symbol: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Cyclical' },
  { symbol: 'T', name: 'AT&T', sector: 'Communication' },
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Financial' },
  { symbol: 'PLD', name: 'Prologis', sector: 'Real Estate' },
  { symbol: 'C', name: 'Citigroup', sector: 'Financial' },
  { symbol: 'MDT', name: 'Medtronic', sector: 'Healthcare' },
  { symbol: 'TJX', name: 'TJX Companies', sector: 'Consumer Cyclical' },
  { symbol: 'BA', name: 'Boeing', sector: 'Industrials' },
  { symbol: 'ADP', name: 'ADP', sector: 'Industrials' },
  { symbol: 'DE', name: 'Deere & Co', sector: 'Industrials' },
  { symbol: 'CB', name: 'Chubb', sector: 'Financial' },
  { symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Financial' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Technology' },
  { symbol: 'ADI', name: 'Analog Devices', sector: 'Technology' },
  { symbol: 'BMY', name: 'Bristol-Myers', sector: 'Healthcare' },
  { symbol: 'MU', name: 'Micron', sector: 'Technology' },
  { symbol: 'UPS', name: 'UPS', sector: 'Industrials' },
  { symbol: 'CVS', name: 'CVS Health', sector: 'Healthcare' },
  { symbol: 'LULU', name: 'Lululemon', sector: 'Consumer Cyclical' },
  { symbol: 'AMT', name: 'American Tower', sector: 'Real Estate' },
  { symbol: 'CI', name: 'Cigna', sector: 'Healthcare' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer Cyclical' },
  { symbol: 'MDLZ', name: 'Mondelez', sector: 'Consumer Defensive' },
  { symbol: 'FI', name: 'Fiserv', sector: 'Technology' },
  { symbol: 'HCA', name: 'HCA Healthcare', sector: 'Healthcare' },
  { symbol: 'NKE', name: 'Nike', sector: 'Consumer Cyclical' },
  { symbol: 'ZTS', name: 'Zoetis', sector: 'Healthcare' },
  { symbol: 'PGR', name: 'Progressive', sector: 'Financial' },
  { symbol: 'SLB', name: 'Schlumberger', sector: 'Energy' },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy' },
  { symbol: 'KLAC', name: 'KLA Corp', sector: 'Technology' },
  { symbol: 'SNPS', name: 'Synopsys', sector: 'Technology' },
  { symbol: 'MO', name: 'Altria', sector: 'Consumer Defensive' },
  { symbol: 'SO', name: 'Southern Co', sector: 'Utilities' },
  { symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Materials' },
  { symbol: 'CDNS', name: 'Cadence Design', sector: 'Technology' },
  { symbol: 'EQIX', name: 'Equinix', sector: 'Real Estate' },
  { symbol: 'ICE', name: 'Intercontinental', sector: 'Financial' },
  { symbol: 'CME', name: 'CME Group', sector: 'Financial' },
  { symbol: 'WM', name: 'Waste Management', sector: 'Industrials' },
  { symbol: 'CSX', name: 'CSX Corp', sector: 'Industrials' },
  { symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer Defensive' },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities' },
  { symbol: 'BDX', name: 'Becton Dickinson', sector: 'Healthcare' },
  { symbol: 'ITW', name: 'Illinois Tool', sector: 'Industrials' },
  { symbol: 'MCK', name: 'McKesson', sector: 'Healthcare' },
  { symbol: 'PYPL', name: 'PayPal', sector: 'Financial' },
  { symbol: 'APH', name: 'Amphenol', sector: 'Technology' },
  { symbol: 'PH', name: 'Parker-Hannifin', sector: 'Industrials' },
  { symbol: 'TGT', name: 'Target', sector: 'Consumer Defensive' },
  { symbol: 'ECL', name: 'Ecolab', sector: 'Materials' },
  { symbol: 'EMR', name: 'Emerson Electric', sector: 'Industrials' },
  { symbol: 'GD', name: 'General Dynamics', sector: 'Industrials' },
  { symbol: 'ORLY', name: 'OReilly Auto', sector: 'Consumer Cyclical' },
  { symbol: 'NXPI', name: 'NXP Semi', sector: 'Technology' },
  { symbol: 'MCO', name: 'Moodys', sector: 'Financial' },
  { symbol: 'FDX', name: 'FedEx', sector: 'Industrials' },
  { symbol: 'MAR', name: 'Marriott', sector: 'Consumer Cyclical' },
  { symbol: 'HPE', name: 'Hewlett Packard', sector: 'Technology' },
  { symbol: 'AON', name: 'Aon', sector: 'Financial' },
  { symbol: 'TT', name: 'Trane Tech', sector: 'Industrials' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { symbol: 'ROP', name: 'Roper Tech', sector: 'Technology' },
  { symbol: 'PCAR', name: 'PACCAR', sector: 'Industrials' },
  { symbol: 'MSCI', name: 'MSCI Inc', sector: 'Financial' },
  { symbol: 'AJG', name: 'Arthur J Gallagher', sector: 'Financial' },
  { symbol: 'COF', name: 'Capital One', sector: 'Financial' },
  { symbol: 'FCX', name: 'Freeport-McMoRan', sector: 'Materials' },
  { symbol: 'MPC', name: 'Marathon Petro', sector: 'Energy' },
  { symbol: 'NSC', name: 'Norfolk Southern', sector: 'Industrials' },
  { symbol: 'OXY', name: 'Occidental', sector: 'Energy' },
  { symbol: 'ADSK', name: 'Autodesk', sector: 'Technology' },
  { symbol: 'AZO', name: 'AutoZone', sector: 'Consumer Cyclical' },
  { symbol: 'DXCM', name: 'DexCom', sector: 'Healthcare' },
  { symbol: 'NOC', name: 'Northrop Grumman', sector: 'Industrials' },
  { symbol: 'MRVL', name: 'Marvell Tech', sector: 'Technology' },
  { symbol: 'MCHP', name: 'Microchip', sector: 'Technology' },
  { symbol: 'WDAY', name: 'Workday', sector: 'Technology' },
  { symbol: 'CTAS', name: 'Cintas', sector: 'Industrials' },
  { symbol: 'MNST', name: 'Monster Bev', sector: 'Consumer Defensive' },
  { symbol: 'WELL', name: 'Welltower', sector: 'Real Estate' },
  { symbol: 'CARR', name: 'Carrier Global', sector: 'Industrials' },
  { symbol: 'AIG', name: 'AIG', sector: 'Financial' },
  { symbol: 'WMB', name: 'Williams Cos', sector: 'Energy' },
  { symbol: 'CCI', name: 'Crown Castle', sector: 'Real Estate' },
  { symbol: 'HLT', name: 'Hilton', sector: 'Consumer Cyclical' },
  { symbol: 'IDXX', name: 'IDEXX Labs', sector: 'Healthcare' },
  { symbol: 'TRV', name: 'Travelers', sector: 'Financial' },
  { symbol: 'DHI', name: 'DR Horton', sector: 'Consumer Cyclical' },
  { symbol: 'MET', name: 'MetLife', sector: 'Financial' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate' },
  { symbol: 'SRE', name: 'Sempra', sector: 'Utilities' },
  { symbol: 'GWW', name: 'WW Grainger', sector: 'Industrials' },
  { symbol: 'BK', name: 'BNY Mellon', sector: 'Financial' },
  { symbol: 'AEP', name: 'American Electric', sector: 'Utilities' },
  { symbol: 'SPG', name: 'Simon Property', sector: 'Real Estate' },
  { symbol: 'ROST', name: 'Ross Stores', sector: 'Consumer Cyclical' },
  { symbol: 'O', name: 'Realty Income', sector: 'Real Estate' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper', sector: 'Consumer Defensive' },
  { symbol: 'D', name: 'Dominion Energy', sector: 'Utilities' },
  { symbol: 'HES', name: 'Hess', sector: 'Energy' },
  { symbol: 'STZ', name: 'Constellation', sector: 'Consumer Defensive' },
  { symbol: 'AMP', name: 'Ameriprise', sector: 'Financial' },
  { symbol: 'PAYX', name: 'Paychex', sector: 'Industrials' },
  { symbol: 'CTVA', name: 'Corteva', sector: 'Materials' },
  { symbol: 'EA', name: 'Electronic Arts', sector: 'Communication' },
  { symbol: 'YUM', name: 'Yum Brands', sector: 'Consumer Cyclical' },
  { symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy' },
  { symbol: 'DLR', name: 'Digital Realty', sector: 'Real Estate' },
  { symbol: 'VLO', name: 'Valero Energy', sector: 'Energy' },
  { symbol: 'CMI', name: 'Cummins', sector: 'Industrials' },
  { symbol: 'OTIS', name: 'Otis Worldwide', sector: 'Industrials' },
  { symbol: 'EXC', name: 'Exelon', sector: 'Utilities' },
  { symbol: 'JCI', name: 'Johnson Controls', sector: 'Industrials' },
  { symbol: 'GIS', name: 'General Mills', sector: 'Consumer Defensive' },
  { symbol: 'AME', name: 'AMETEK', sector: 'Industrials' },
  { symbol: 'GPN', name: 'Global Payments', sector: 'Financial' },
  { symbol: 'KR', name: 'Kroger', sector: 'Consumer Defensive' },
  { symbol: 'FIS', name: 'FIS', sector: 'Technology' },
  { symbol: 'XEL', name: 'Xcel Energy', sector: 'Utilities' },
  { symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy' },
  { symbol: 'FAST', name: 'Fastenal', sector: 'Industrials' },
  { symbol: 'ED', name: 'Consolidated Edison', sector: 'Utilities' },
  { symbol: 'COR', name: 'Cencora', sector: 'Healthcare' },
  { symbol: 'GEHC', name: 'GE HealthCare', sector: 'Healthcare' },
  { symbol: 'VRSK', name: 'Verisk', sector: 'Industrials' },
  { symbol: 'CSGP', name: 'CoStar Group', sector: 'Real Estate' },
  { symbol: 'PEG', name: 'PSEG', sector: 'Utilities' },
  { symbol: 'HSY', name: 'Hershey', sector: 'Consumer Defensive' },
  { symbol: 'ODFL', name: 'Old Dominion', sector: 'Industrials' },
  { symbol: 'LEN', name: 'Lennar', sector: 'Consumer Cyclical' },
  { symbol: 'KHC', name: 'Kraft Heinz', sector: 'Consumer Defensive' },
  { symbol: 'HPQ', name: 'HP Inc', sector: 'Technology' },
  { symbol: 'GLW', name: 'Corning', sector: 'Technology' },
  { symbol: 'RCL', name: 'Royal Caribbean', sector: 'Consumer Cyclical' },
  { symbol: 'ON', name: 'ON Semi', sector: 'Technology' },
  { symbol: 'CDW', name: 'CDW Corp', sector: 'Technology' },
  { symbol: 'VMC', name: 'Vulcan Materials', sector: 'Materials' },
  { symbol: 'MLM', name: 'Martin Marietta', sector: 'Materials' },
  { symbol: 'EFX', name: 'Equifax', sector: 'Industrials' },
  { symbol: 'CBRE', name: 'CBRE Group', sector: 'Real Estate' },
  { symbol: 'WY', name: 'Weyerhaeuser', sector: 'Real Estate' },
  { symbol: 'DAL', name: 'Delta Air Lines', sector: 'Industrials' },
  { symbol: 'HAL', name: 'Halliburton', sector: 'Energy' },
  { symbol: 'DVN', name: 'Devon Energy', sector: 'Energy' },
  { symbol: 'FANG', name: 'Diamondback', sector: 'Energy' },
  { symbol: 'WEC', name: 'WEC Energy', sector: 'Utilities' },
  { symbol: 'AWK', name: 'American Water', sector: 'Utilities' },
  { symbol: 'EIX', name: 'Edison Intl', sector: 'Utilities' },
  { symbol: 'DTE', name: 'DTE Energy', sector: 'Utilities' },
  { symbol: 'FE', name: 'FirstEnergy', sector: 'Utilities' },
  { symbol: 'PPL', name: 'PPL Corp', sector: 'Utilities' },
  { symbol: 'ETR', name: 'Entergy', sector: 'Utilities' },
  { symbol: 'AEE', name: 'Ameren', sector: 'Utilities' },
  { symbol: 'CMS', name: 'CMS Energy', sector: 'Utilities' },
  { symbol: 'CNP', name: 'CenterPoint', sector: 'Utilities' },
  { symbol: 'ES', name: 'Eversource', sector: 'Utilities' },
  { symbol: 'VICI', name: 'VICI Properties', sector: 'Real Estate' },
  { symbol: 'SBAC', name: 'SBA Comms', sector: 'Real Estate' },
  { symbol: 'AVB', name: 'AvalonBay', sector: 'Real Estate' },
  { symbol: 'EQR', name: 'Equity Residential', sector: 'Real Estate' },
  { symbol: 'ARE', name: 'Alexandria RE', sector: 'Real Estate' },
  { symbol: 'VTR', name: 'Ventas', sector: 'Real Estate' },
  { symbol: 'EXR', name: 'Extra Space', sector: 'Real Estate' },
  { symbol: 'IRM', name: 'Iron Mountain', sector: 'Real Estate' },
  { symbol: 'MAA', name: 'Mid-America', sector: 'Real Estate' },
  { symbol: 'ESS', name: 'Essex Property', sector: 'Real Estate' },
  { symbol: 'UDR', name: 'UDR Inc', sector: 'Real Estate' },
  { symbol: 'HST', name: 'Host Hotels', sector: 'Real Estate' },
  { symbol: 'KIM', name: 'Kimco', sector: 'Real Estate' },
  { symbol: 'BXP', name: 'Boston Properties', sector: 'Real Estate' },
  
  // --- TECH MOMENTUM & GROWTH ---
  { symbol: 'PLTR', name: 'Palantir', sector: 'Technology' },
  { symbol: 'SMCI', name: 'Super Micro', sector: 'Technology' },
  { symbol: 'ARM', name: 'Arm Holdings', sector: 'Technology' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Technology' },
  { symbol: 'NET', name: 'Cloudflare', sector: 'Technology' },
  { symbol: 'DDOG', name: 'Datadog', sector: 'Technology' },
  { symbol: 'ZS', name: 'Zscaler', sector: 'Technology' },
  { symbol: 'MDB', name: 'MongoDB', sector: 'Technology' },
  { symbol: 'HUBS', name: 'HubSpot', sector: 'Technology' },
  { symbol: 'TEAM', name: 'Atlassian', sector: 'Technology' },
  { symbol: 'TTD', name: 'The Trade Desk', sector: 'Technology' },
  { symbol: 'SQ', name: 'Block', sector: 'Financial' },
  { symbol: 'ROKU', name: 'Roku', sector: 'Communication' },
  { symbol: 'SHOP', name: 'Shopify', sector: 'Technology' },
  { symbol: 'U', name: 'Unity', sector: 'Technology' },
  { symbol: 'RBLX', name: 'Roblox', sector: 'Technology' },
  { symbol: 'COIN', name: 'Coinbase', sector: 'Financial' },
  { symbol: 'HOOD', name: 'Robinhood', sector: 'Financial' },
  { symbol: 'DKNG', name: 'DraftKings', sector: 'Consumer Cyclical' },
  { symbol: 'PATH', name: 'UiPath', sector: 'Technology' },
  { symbol: 'AFRM', name: 'Affirm', sector: 'Financial' },
  { symbol: 'UPST', name: 'Upstart', sector: 'Financial' },
  { symbol: 'SOFI', name: 'SoFi Tech', sector: 'Financial' },
  { symbol: 'CVNA', name: 'Carvana', sector: 'Consumer Cyclical' },
  { symbol: 'RDDT', name: 'Reddit', sector: 'Technology' },
  { symbol: 'APP', name: 'AppLovin', sector: 'Technology' },
  { symbol: 'IOT', name: 'Samsara', sector: 'Technology' },
  { symbol: 'DT', name: 'Dynatrace', sector: 'Technology' },
  { symbol: 'ESTC', name: 'Elastic', sector: 'Technology' },
  { symbol: 'GTLB', name: 'GitLab', sector: 'Technology' },
  { symbol: 'HCP', name: 'HashiCorp', sector: 'Technology' },
  { symbol: 'MNDY', name: 'Monday.com', sector: 'Technology' },
  { symbol: 'SNOW', name: 'Snowflake', sector: 'Technology' },
  { symbol: 'CFLT', name: 'Confluent', sector: 'Technology' },
  { symbol: 'AI', name: 'C3.ai', sector: 'Technology' },
  { symbol: 'IONQ', name: 'IonQ', sector: 'Technology' },
  { symbol: 'QUBT', name: 'Qubt', sector: 'Technology' },
  { symbol: 'RGTI', name: 'Rigetti', sector: 'Technology' },
  { symbol: 'QBTS', name: 'D-Wave', sector: 'Technology' },
  { symbol: 'PLUG', name: 'Plug Power', sector: 'Industrials' },
  { symbol: 'FCEL', name: 'FuelCell', sector: 'Industrials' },
  { symbol: 'RUN', name: 'Sunrun', sector: 'Utilities' },
  { symbol: 'ENPH', name: 'Enphase', sector: 'Technology' },
  { symbol: 'FSLR', name: 'First Solar', sector: 'Technology' },
  { symbol: 'SEDG', name: 'SolarEdge', sector: 'Technology' },
  { symbol: 'NIO', name: 'NIO Inc', sector: 'Consumer Cyclical' },
  { symbol: 'XPEV', name: 'XPeng', sector: 'Consumer Cyclical' },
  { symbol: 'LI', name: 'Li Auto', sector: 'Consumer Cyclical' },
  { symbol: 'LCID', name: 'Lucid', sector: 'Consumer Cyclical' },
  { symbol: 'RIVN', name: 'Rivian', sector: 'Consumer Cyclical' },
  { symbol: 'GME', name: 'GameStop', sector: 'Consumer Cyclical' },
  { symbol: 'AMC', name: 'AMC', sector: 'Communication' },
  { symbol: 'MARA', name: 'Marathon Digital', sector: 'Technology' },
  { symbol: 'RIOT', name: 'Riot Platforms', sector: 'Technology' },
  { symbol: 'CLSK', name: 'CleanSpark', sector: 'Technology' },
  { symbol: 'HUT', name: 'Hut 8', sector: 'Technology' },
  { symbol: 'MSTR', name: 'MicroStrategy', sector: 'Technology' },
  { symbol: 'BITO', name: 'Bitcoin Strategy', sector: 'ETF' },
  { symbol: 'IBIT', name: 'iShares Bitcoin', sector: 'ETF' },
  { symbol: 'FBTC', name: 'Fidelity Bitcoin', sector: 'ETF' },
  { symbol: 'ETHE', name: 'Grayscale Eth', sector: 'ETF' },
  { symbol: 'OKLO', name: 'Oklo Inc', sector: 'Energy' },
  { symbol: 'ASTS', name: 'AST SpaceMobile', sector: 'Technology' },
  { symbol: 'RKLB', name: 'Rocket Lab', sector: 'Industrials' },
  { symbol: 'LUNR', name: 'Intuitive Machines', sector: 'Industrials' },
  { symbol: 'SPCE', name: 'Virgin Galactic', sector: 'Industrials' },
  { symbol: 'VRT', name: 'Vertiv', sector: 'Industrials' },
  { symbol: 'GEV', name: 'GE Vernova', sector: 'Industrials' },
  { symbol: 'CAVA', name: 'CAVA Group', sector: 'Consumer Cyclical' },
  { symbol: 'ALAB', name: 'Astera Labs', sector: 'Technology' },
  { symbol: 'DJT', name: 'Trump Media', sector: 'Technology' },
  { symbol: 'CHWY', name: 'Chewy', sector: 'Consumer Cyclical' },
  { symbol: 'WING', name: 'Wingstop', sector: 'Consumer Cyclical' },
  { symbol: 'CELH', name: 'Celsius', sector: 'Consumer Defensive' },
  { symbol: 'ELF', name: 'e.l.f. Beauty', sector: 'Consumer Defensive' },
  { symbol: 'ONON', name: 'On Holding', sector: 'Consumer Cyclical' },
  { symbol: 'DECK', name: 'Deckers', sector: 'Consumer Cyclical' },
  { symbol: 'BIRK', name: 'Birkenstock', sector: 'Consumer Cyclical' },
  { symbol: 'CROX', name: 'Crocs', sector: 'Consumer Cyclical' },
  { symbol: 'ANF', name: 'Abercrombie', sector: 'Consumer Cyclical' },
  { symbol: 'URBN', name: 'Urban Outfitters', sector: 'Consumer Cyclical' },
  { symbol: 'GPS', name: 'Gap Inc', sector: 'Consumer Cyclical' },
  { symbol: 'BJ', name: 'BJs Wholesale', sector: 'Consumer Defensive' },
  { symbol: 'DLTR', name: 'Dollar Tree', sector: 'Consumer Defensive' },
  { symbol: 'DG', name: 'Dollar General', sector: 'Consumer Defensive' },
  { symbol: 'NVO', name: 'Novo Nordisk', sector: 'Healthcare' },
  { symbol: 'VKTX', name: 'Viking Therapeutics', sector: 'Healthcare' },
  { symbol: 'CRSP', name: 'CRISPR', sector: 'Healthcare' },
  { symbol: 'NTLA', name: 'Intellia', sector: 'Healthcare' },
  { symbol: 'BIIB', name: 'Biogen', sector: 'Healthcare' },
  { symbol: 'MRNA', name: 'Moderna', sector: 'Healthcare' },
  { symbol: 'BNTX', name: 'BioNTech', sector: 'Healthcare' },
  { symbol: 'BX', name: 'Blackstone', sector: 'Financial' },
  { symbol: 'KKR', name: 'KKR & Co', sector: 'Financial' },
  { symbol: 'APO', name: 'Apollo Global', sector: 'Financial' },
  { symbol: 'ARES', name: 'Ares Mgmt', sector: 'Financial' },
  { symbol: 'PXD', name: 'Pioneer', sector: 'Energy' },
  { symbol: 'TRP', name: 'TC Energy', sector: 'Energy' },
  { symbol: 'ENB', name: 'Enbridge', sector: 'Energy' },
  { symbol: 'F', name: 'Ford', sector: 'Consumer Cyclical' },
  { symbol: 'GM', name: 'General Motors', sector: 'Consumer Cyclical' },
  { symbol: 'STLA', name: 'Stellantis', sector: 'Consumer Cyclical' },
  { symbol: 'TM', name: 'Toyota', sector: 'Consumer Cyclical' },
  { symbol: 'HMC', name: 'Honda', sector: 'Consumer Cyclical' },
  { symbol: 'CIFR', name: 'Cipher', sector: 'Technology' },

  // --- CONSUMER & RETAIL EXPANSION ---
  { symbol: 'ULTA', name: 'Ulta Beauty', sector: 'Consumer Cyclical' },
  { symbol: 'TSCO', name: 'Tractor Supply', sector: 'Consumer Cyclical' },
  { symbol: 'SYY', name: 'Sysco', sector: 'Consumer Defensive' },
  { symbol: 'ADM', name: 'Archer-Daniels', sector: 'Consumer Defensive' },
  { symbol: 'CAG', name: 'Conagra', sector: 'Consumer Defensive' },
  { symbol: 'CPB', name: 'Campbell Soup', sector: 'Consumer Defensive' },
  { symbol: 'MKC', name: 'McCormick', sector: 'Consumer Defensive' },
  { symbol: 'HRL', name: 'Hormel', sector: 'Consumer Defensive' },
  { symbol: 'SJM', name: 'JM Smucker', sector: 'Consumer Defensive' },
  { symbol: 'K', name: 'Kellanova', sector: 'Consumer Defensive' },
  { symbol: 'CLX', name: 'Clorox', sector: 'Consumer Defensive' },
  { symbol: 'CHD', name: 'Church & Dwight', sector: 'Consumer Defensive' },
  { symbol: 'TAP', name: 'Molson Coors', sector: 'Consumer Defensive' },
  { symbol: 'BF.B', name: 'Brown-Forman', sector: 'Consumer Defensive' },
  { symbol: 'DRI', name: 'Darden', sector: 'Consumer Cyclical' },
  { symbol: 'DPZ', name: 'Domino\'s', sector: 'Consumer Cyclical' },
  { symbol: 'MCD', name: 'McDonald\'s', sector: 'Consumer Cyclical' },
  { symbol: 'CMG', name: 'Chipotle', sector: 'Consumer Cyclical' },
  { symbol: 'QSR', name: 'Restaurant Brands', sector: 'Consumer Cyclical' },
  { symbol: 'WEN', name: 'Wendy\'s', sector: 'Consumer Cyclical' },
  { symbol: 'PZZA', name: 'Papa John\'s', sector: 'Consumer Cyclical' },
  { symbol: 'TXRH', name: 'Texas Roadhouse', sector: 'Consumer Cyclical' },
  { symbol: 'CAKE', name: 'Cheesecake Factory', sector: 'Consumer Cyclical' },
  { symbol: 'BLMN', name: 'Bloomin\' Brands', sector: 'Consumer Cyclical' },
  { symbol: 'EAT', name: 'Brinker', sector: 'Consumer Cyclical' },
  { symbol: 'SHAK', name: 'Shake Shack', sector: 'Consumer Cyclical' },
  { symbol: 'SG', name: 'Sweetgreen', sector: 'Consumer Cyclical' },
  { symbol: 'BROS', name: 'Dutch Bros', sector: 'Consumer Cyclical' },
  
  // --- TECH & SOFTWARE (MID-CAP GROWTH) ---
  { symbol: 'DOCU', name: 'DocuSign', sector: 'Technology' },
  { symbol: 'DBX', name: 'Dropbox', sector: 'Technology' },
  { symbol: 'BOX', name: 'Box', sector: 'Technology' },
  { symbol: 'SMAR', name: 'Smartsheet', sector: 'Technology' },
  { symbol: 'ASAN', name: 'Asana', sector: 'Technology' },
  { symbol: 'WK', name: 'Workiva', sector: 'Technology' },
  { symbol: 'BL', name: 'BlackLine', sector: 'Technology' },
  { symbol: 'AYX', name: 'Alteryx', sector: 'Technology' },
  { symbol: 'NEWR', name: 'New Relic', sector: 'Technology' },
  { symbol: 'APPN', name: 'Appian', sector: 'Technology' },
  { symbol: 'PD', name: 'PagerDuty', sector: 'Technology' },
  { symbol: 'ZM', name: 'Zoom', sector: 'Technology' },
  { symbol: 'FSLY', name: 'Fastly', sector: 'Technology' },
  { symbol: 'NET', name: 'Cloudflare', sector: 'Technology' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Technology' },
  { symbol: 'OKTA', name: 'Okta', sector: 'Technology' },
  { symbol: 'PANW', name: 'Palo Alto', sector: 'Technology' },
  { symbol: 'FTNT', name: 'Fortinet', sector: 'Technology' },
  { symbol: 'CHKP', name: 'Check Point', sector: 'Technology' },
  { symbol: 'CYBR', name: 'CyberArk', sector: 'Technology' },
  { symbol: 'TENB', name: 'Tenable', sector: 'Technology' },
  { symbol: 'RPD', name: 'Rapid7', sector: 'Technology' },
  { symbol: 'QLYS', name: 'Qualys', sector: 'Technology' },
  { symbol: 'VRNS', name: 'Varonis', sector: 'Technology' },
  { symbol: 'NTNX', name: 'Nutanix', sector: 'Technology' },
  { symbol: 'PSTG', name: 'Pure Storage', sector: 'Technology' },
  { symbol: 'TDC', name: 'Teradata', sector: 'Technology' },
  { symbol: 'GWRE', name: 'Guidewire', sector: 'Technology' },
  { symbol: 'PEGA', name: 'Pegasystems', sector: 'Technology' },
  { symbol: 'COMM', name: 'CommScope', sector: 'Technology' },
  { symbol: 'CIEN', name: 'Ciena', sector: 'Technology' },
  { symbol: 'LITE', name: 'Lumentum', sector: 'Technology' },
  { symbol: 'VIAV', name: 'Viavi', sector: 'Technology' },
  { symbol: 'ACIA', name: 'Acacia', sector: 'Technology' },
  { symbol: 'INFN', name: 'Infinera', sector: 'Technology' },
  { symbol: 'VSAT', name: 'Viasat', sector: 'Technology' },
  { symbol: 'SATS', name: 'EchoStar', sector: 'Technology' },
  { symbol: 'IRDM', name: 'Iridium', sector: 'Technology' },
  { symbol: 'GSAT', name: 'Globalstar', sector: 'Technology' },
  { symbol: 'CRCL', name: 'Circle', sector: 'Technology' },
  { symbol: 'CRWV', name: 'CoreWeave', sector: 'Technology' },
  { symbol: 'IREN', name: 'IREN', sector: 'Technology' },

  // --- FINANCIALS: REGIONAL BANKS & INSURANCE ---
  { symbol: 'USB', name: 'US Bancorp', sector: 'Financial' },
  { symbol: 'PNC', name: 'PNC Financial', sector: 'Financial' },
  { symbol: 'TFC', name: 'Truist', sector: 'Financial' },
  { symbol: 'FITB', name: 'Fifth Third', sector: 'Financial' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Financial' },
  { symbol: 'HBAN', name: 'Huntington', sector: 'Financial' },
  { symbol: 'RF', name: 'Regions', sector: 'Financial' },
  { symbol: 'CFG', name: 'Citizens', sector: 'Financial' },
  { symbol: 'MTB', name: 'M&T Bank', sector: 'Financial' },
  { symbol: 'CMA', name: 'Comerica', sector: 'Financial' },
  { symbol: 'ZION', name: 'Zions', sector: 'Financial' },
  { symbol: 'WAL', name: 'Western Alliance', sector: 'Financial' },
  { symbol: 'EWBC', name: 'East West', sector: 'Financial' },
  { symbol: 'BOKF', name: 'BOK Financial', sector: 'Financial' },
  { symbol: 'CFR', name: 'Cullen/Frost', sector: 'Financial' },
  { symbol: 'CBSH', name: 'Commerce', sector: 'Financial' },
  { symbol: 'WBS', name: 'Webster', sector: 'Financial' },
  { symbol: 'PNFP', name: 'Pinnacle', sector: 'Financial' },
  { symbol: 'PB', name: 'Prosperity', sector: 'Financial' },
  { symbol: 'FHN', name: 'First Horizon', sector: 'Financial' },
  { symbol: 'SNV', name: 'Synovus', sector: 'Financial' },
  { symbol: 'VLY', name: 'Valley National', sector: 'Financial' },
  { symbol: 'BOH', name: 'Bank of Hawaii', sector: 'Financial' },
  { symbol: 'OZK', name: 'Bank OZK', sector: 'Financial' },
  { symbol: 'AFL', name: 'Aflac', sector: 'Financial' },
  { symbol: 'PRU', name: 'Prudential', sector: 'Financial' },
  { symbol: 'HIG', name: 'Hartford', sector: 'Financial' },
  { symbol: 'ALL', name: 'Allstate', sector: 'Financial' },
  { symbol: 'WRB', name: 'WR Berkley', sector: 'Financial' },
  { symbol: 'CINF', name: 'Cincinnati Fin', sector: 'Financial' },
  { symbol: 'L', name: 'Loews', sector: 'Financial' },
  { symbol: 'CNA', name: 'CNA Financial', sector: 'Financial' },
  { symbol: 'MKL', name: 'Markel', sector: 'Financial' },
  { symbol: 'RE', name: 'Everest Re', sector: 'Financial' },
  { symbol: 'ACGL', name: 'Arch Capital', sector: 'Financial' },
  { symbol: 'AXS', name: 'Axis Capital', sector: 'Financial' },
  { symbol: 'URI', name: 'United Rentals', sector: 'Financial' },

  // --- HEALTHCARE: BIOTECH, DEVICES & SERVICES ---
  { symbol: 'AMGN', name: 'Amgen', sector: 'Healthcare' },
  { symbol: 'GILD', name: 'Gilead', sector: 'Healthcare' },
  { symbol: 'VRTX', name: 'Vertex', sector: 'Healthcare' },
  { symbol: 'REGN', name: 'Regeneron', sector: 'Healthcare' },
  { symbol: 'ILMN', name: 'Illumina', sector: 'Healthcare' },
  { symbol: 'ALNY', name: 'Alnylam', sector: 'Healthcare' },
  { symbol: 'INCY', name: 'Incyte', sector: 'Healthcare' },
  { symbol: 'BMRN', name: 'BioMarin', sector: 'Healthcare' },
  { symbol: 'UTHR', name: 'United Therapeutics', sector: 'Healthcare' },
  { symbol: 'NBIX', name: 'Neurocrine', sector: 'Healthcare' },
  { symbol: 'TECH', name: 'Bio-Techne', sector: 'Healthcare' },
  { symbol: 'RGEN', name: 'Repligen', sector: 'Healthcare' },
  { symbol: 'CRL', name: 'Charles River', sector: 'Healthcare' },
  { symbol: 'IQV', name: 'IQVIA', sector: 'Healthcare' },
  { symbol: 'ICLR', name: 'Icon', sector: 'Healthcare' },
  { symbol: 'MEDP', name: 'Medpace', sector: 'Healthcare' },
  { symbol: 'BSX', name: 'Boston Scientific', sector: 'Healthcare' },
  { symbol: 'EW', name: 'Edwards Life', sector: 'Healthcare' },
  { symbol: 'ZBH', name: 'Zimmer Biomet', sector: 'Healthcare' },
  { symbol: 'ALGN', name: 'Align Tech', sector: 'Healthcare' },
  { symbol: 'COO', name: 'Cooper', sector: 'Healthcare' },
  { symbol: 'RMD', name: 'ResMed', sector: 'Healthcare' },
  { symbol: 'HCA', name: 'HCA Healthcare', sector: 'Healthcare' },
  { symbol: 'UHS', name: 'Universal Health', sector: 'Healthcare' },
  { symbol: 'THC', name: 'Tenet', sector: 'Healthcare' },
  { symbol: 'ACHC', name: 'Acadia', sector: 'Healthcare' },
  { symbol: 'ENSG', name: 'Ensign Group', sector: 'Healthcare' },
  { symbol: 'EHC', name: 'Encompass', sector: 'Healthcare' },
  { symbol: 'MOH', name: 'Molina', sector: 'Healthcare' },
  { symbol: 'CNC', name: 'Centene', sector: 'Healthcare' },
  { symbol: 'HUM', name: 'Humana', sector: 'Healthcare' },
  { symbol: 'CI', name: 'Cigna', sector: 'Healthcare' },
  { symbol: 'CVS', name: 'CVS Health', sector: 'Healthcare' },
  { symbol: 'WBA', name: 'Walgreens', sector: 'Healthcare' },
  
  // --- REAL ESTATE (REITS) ---
  { symbol: 'PLD', name: 'Prologis', sector: 'Real Estate' },
  { symbol: 'AMT', name: 'American Tower', sector: 'Real Estate' },
  { symbol: 'CCI', name: 'Crown Castle', sector: 'Real Estate' },
  { symbol: 'EQIX', name: 'Equinix', sector: 'Real Estate' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate' },
  { symbol: 'O', name: 'Realty Income', sector: 'Real Estate' },
  { symbol: 'SPG', name: 'Simon Property', sector: 'Real Estate' },
  { symbol: 'VICI', name: 'VICI Properties', sector: 'Real Estate' },
  { symbol: 'CSGP', name: 'CoStar', sector: 'Real Estate' },
  { symbol: 'WELL', name: 'Welltower', sector: 'Real Estate' },
  { symbol: 'DLR', name: 'Digital Realty', sector: 'Real Estate' },
  { symbol: 'SBAC', name: 'SBA Comms', sector: 'Real Estate' },
  { symbol: 'CBRE', name: 'CBRE Group', sector: 'Real Estate' },
  { symbol: 'WY', name: 'Weyerhaeuser', sector: 'Real Estate' },
  { symbol: 'AVB', name: 'AvalonBay', sector: 'Real Estate' },
  { symbol: 'EQR', name: 'Equity Residential', sector: 'Real Estate' },
  { symbol: 'INVH', name: 'Invitation Homes', sector: 'Real Estate' },
  { symbol: 'EXR', name: 'Extra Space', sector: 'Real Estate' },
  { symbol: 'MAA', name: 'Mid-America', sector: 'Real Estate' },
  { symbol: 'ESS', name: 'Essex', sector: 'Real Estate' },
  { symbol: 'UDR', name: 'UDR Inc', sector: 'Real Estate' },
  { symbol: 'HST', name: 'Host Hotels', sector: 'Real Estate' },
  { symbol: 'VTR', name: 'Ventas', sector: 'Real Estate' },
  { symbol: 'ARE', name: 'Alexandria', sector: 'Real Estate' },
  { symbol: 'BXP', name: 'Boston Properties', sector: 'Real Estate' },
  { symbol: 'CPT', name: 'Camden', sector: 'Real Estate' },
  { symbol: 'GLPI', name: 'Gaming and Leisure', sector: 'Real Estate' },
  { symbol: 'KIM', name: 'Kimco', sector: 'Real Estate' },
  { symbol: 'REG', name: 'Regency', sector: 'Real Estate' },
  { symbol: 'FRT', name: 'Federal Realty', sector: 'Real Estate' },
  { symbol: 'OHI', name: 'Omega Health', sector: 'Real Estate' },
  { symbol: 'MPW', name: 'Medical Prop', sector: 'Real Estate' },
  { symbol: 'STWD', name: 'Starwood', sector: 'Real Estate' },
  { symbol: 'NLY', name: 'Annaly', sector: 'Real Estate' },
  { symbol: 'AGNC', name: 'AGNC Inv', sector: 'Real Estate' },
  { symbol: 'ABR', name: 'Arbor Realty', sector: 'Real Estate' },
  { symbol: 'IRM', name: 'Iron Mountain', sector: 'Real Estate' },
  { symbol: 'LAMR', name: 'Lamar', sector: 'Real Estate' },
  
  // --- UTILITIES & INFRASTRUCTURE ---
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities' },
  { symbol: 'SO', name: 'Southern Co', sector: 'Utilities' },
  { symbol: 'AEP', name: 'American Electric', sector: 'Utilities' },
  { symbol: 'SRE', name: 'Sempra', sector: 'Utilities' },
  { symbol: 'EXC', name: 'Exelon', sector: 'Utilities' },
  { symbol: 'D', name: 'Dominion', sector: 'Utilities' },
  { symbol: 'XEL', name: 'Xcel Energy', sector: 'Utilities' },
  { symbol: 'ED', name: 'Consolidated Edison', sector: 'Utilities' },
  { symbol: 'PEG', name: 'PSEG', sector: 'Utilities' },
  { symbol: 'WEC', name: 'WEC Energy', sector: 'Utilities' },
  { symbol: 'EIX', name: 'Edison Intl', sector: 'Utilities' },
  { symbol: 'DTE', name: 'DTE Energy', sector: 'Utilities' },
  { symbol: 'FE', name: 'FirstEnergy', sector: 'Utilities' },
  { symbol: 'AEE', name: 'Ameren', sector: 'Utilities' },
  { symbol: 'ETR', name: 'Entergy', sector: 'Utilities' },
  { symbol: 'PPL', name: 'PPL Corp', sector: 'Utilities' },
  { symbol: 'CMS', name: 'CMS Energy', sector: 'Utilities' },
  { symbol: 'CNP', name: 'CenterPoint', sector: 'Utilities' },
  { symbol: 'AES', name: 'AES Corp', sector: 'Utilities' },
  { symbol: 'NRG', name: 'NRG Energy', sector: 'Utilities' },
  { symbol: 'VST', name: 'Vistra', sector: 'Utilities' },
  { symbol: 'CEG', name: 'Constellation', sector: 'Utilities' },
  { symbol: 'LNT', name: 'Alliant', sector: 'Utilities' },
  { symbol: 'EVRG', name: 'Evergy', sector: 'Utilities' },
  { symbol: 'ATO', name: 'Atmos', sector: 'Utilities' },
  { symbol: 'NI', name: 'NiSource', sector: 'Utilities' },
  { symbol: 'AWK', name: 'American Water', sector: 'Utilities' },
  { symbol: 'WTRG', name: 'Essential Utilities', sector: 'Utilities' },
  
  // --- INDUSTRIALS: AEROSPACE, DEFENSE & MACHINERY ---
  { symbol: 'RTX', name: 'Raytheon', sector: 'Industrials' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrials' },
  { symbol: 'NOC', name: 'Northrop Grumman', sector: 'Industrials' },
  { symbol: 'GD', name: 'General Dynamics', sector: 'Industrials' },
  { symbol: 'BA', name: 'Boeing', sector: 'Industrials' },
  { symbol: 'LHX', name: 'L3Harris', sector: 'Industrials' },
  { symbol: 'HII', name: 'Huntington Ingalls', sector: 'Industrials' },
  { symbol: 'TXT', name: 'Textron', sector: 'Industrials' },
  { symbol: 'LDOS', name: 'Leidos', sector: 'Industrials' },
  { symbol: 'BAH', name: 'Booz Allen', sector: 'Industrials' },
  { symbol: 'SAIC', name: 'SAIC', sector: 'Industrials' },
  { symbol: 'CACI', name: 'CACI', sector: 'Industrials' },
  { symbol: 'CAT', name: 'Caterpillar', sector: 'Industrials' },
  { symbol: 'DE', name: 'Deere', sector: 'Industrials' },
  { symbol: 'CMI', name: 'Cummins', sector: 'Industrials' },
  { symbol: 'PCAR', name: 'PACCAR', sector: 'Industrials' },
  { symbol: 'ETN', name: 'Eaton', sector: 'Industrials' },
  { symbol: 'ITW', name: 'Illinois Tool', sector: 'Industrials' },
  { symbol: 'PH', name: 'Parker-Hannifin', sector: 'Industrials' },
  { symbol: 'EMR', name: 'Emerson', sector: 'Industrials' },
  { symbol: 'ROK', name: 'Rockwell', sector: 'Industrials' },
  { symbol: 'AME', name: 'AMETEK', sector: 'Industrials' },
  { symbol: 'OTIS', name: 'Otis', sector: 'Industrials' },
  { symbol: 'CARR', name: 'Carrier', sector: 'Industrials' },
  { symbol: 'JCI', name: 'Johnson Controls', sector: 'Industrials' },
  { symbol: 'TT', name: 'Trane', sector: 'Industrials' },
  { symbol: 'LII', name: 'Lennox', sector: 'Industrials' },
  { symbol: 'GWW', name: 'Grainger', sector: 'Industrials' },
  { symbol: 'FAST', name: 'Fastenal', sector: 'Industrials' },
  { symbol: 'PWR', name: 'Quanta', sector: 'Industrials' },
  { symbol: 'EME', name: 'EMCOR', sector: 'Industrials' },
  { symbol: 'VMI', name: 'Valmont', sector: 'Industrials' },
  { symbol: 'XYL', name: 'Xylem', sector: 'Industrials' },
  { symbol: 'PNR', name: 'Pentair', sector: 'Industrials' },
  { symbol: 'DOV', name: 'Dover', sector: 'Industrials' },
  { symbol: 'SWK', name: 'Stanley Black', sector: 'Industrials' },
  { symbol: 'SNA', name: 'Snap-on', sector: 'Industrials' },
  
  // --- TRANSPORTATION & LOGISTICS ---
  { symbol: 'UPS', name: 'UPS', sector: 'Industrials' },
  { symbol: 'FDX', name: 'FedEx', sector: 'Industrials' },
  { symbol: 'UNP', name: 'Union Pacific', sector: 'Industrials' },
  { symbol: 'CSX', name: 'CSX Corp', sector: 'Industrials' },
  { symbol: 'NSC', name: 'Norfolk Southern', sector: 'Industrials' },
  { symbol: 'CP', name: 'CPKC', sector: 'Industrials' },
  { symbol: 'CNI', name: 'Canadian Natl', sector: 'Industrials' },
  { symbol: 'ODFL', name: 'Old Dominion', sector: 'Industrials' },
  { symbol: 'JBHT', name: 'JB Hunt', sector: 'Industrials' },
  { symbol: 'XPO', name: 'XPO Inc', sector: 'Industrials' },
  { symbol: 'SAIA', name: 'Saia', sector: 'Industrials' },
  { symbol: 'KNX', name: 'Knight-Swift', sector: 'Industrials' },
  { symbol: 'DAL', name: 'Delta Air', sector: 'Industrials' },
  { symbol: 'UAL', name: 'United Airlines', sector: 'Industrials' },
  { symbol: 'AAL', name: 'American Airlines', sector: 'Industrials' },
  { symbol: 'LUV', name: 'Southwest', sector: 'Industrials' },
  { symbol: 'ALK', name: 'Alaska Air', sector: 'Industrials' },
  { symbol: 'EXPD', name: 'Expeditors', sector: 'Industrials' },
  { symbol: 'CHRW', name: 'CH Robinson', sector: 'Industrials' },
  
  // --- MATERIALS & CHEMICALS ---
  { symbol: 'LIN', name: 'Linde', sector: 'Materials' },
  { symbol: 'APD', name: 'Air Products', sector: 'Materials' },
  { symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Materials' },
  { symbol: 'PPG', name: 'PPG Industries', sector: 'Materials' },
  { symbol: 'ECL', name: 'Ecolab', sector: 'Materials' },
  { symbol: 'DD', name: 'DuPont', sector: 'Materials' },
  { symbol: 'DOW', name: 'Dow Inc', sector: 'Materials' },
  { symbol: 'LYB', name: 'LyondellBasell', sector: 'Materials' },
  { symbol: 'EMN', name: 'Eastman', sector: 'Materials' },
  { symbol: 'CE', name: 'Celanese', sector: 'Materials' },
  { symbol: 'FCX', name: 'Freeport-McMoRan', sector: 'Materials' },
  { symbol: 'SCCO', name: 'Southern Copper', sector: 'Materials' },
  { symbol: 'NEM', name: 'Newmont', sector: 'Materials' },
  { symbol: 'GOLD', name: 'Barrick', sector: 'Materials' },
  { symbol: 'AEM', name: 'Agnico Eagle', sector: 'Materials' },
  { symbol: 'NUE', name: 'Nucor', sector: 'Materials' },
  { symbol: 'STLD', name: 'Steel Dynamics', sector: 'Materials' },
  { symbol: 'CLF', name: 'Cleveland-Cliffs', sector: 'Materials' },
  { symbol: 'X', name: 'US Steel', sector: 'Materials' },
  { symbol: 'AA', name: 'Alcoa', sector: 'Materials' },
  { symbol: 'MLM', name: 'Martin Marietta', sector: 'Materials' },
  { symbol: 'VMC', name: 'Vulcan Materials', sector: 'Materials' },
  { symbol: 'ALB', name: 'Albemarle', sector: 'Materials' },
  { symbol: 'SQM', name: 'Sociedad Quimica', sector: 'Materials' },
  { symbol: 'CF', name: 'CF Industries', sector: 'Materials' },
  { symbol: 'MOS', name: 'Mosaic', sector: 'Materials' },
  { symbol: 'FMC', name: 'FMC Corp', sector: 'Materials' },
  { symbol: 'CTVA', name: 'Corteva', sector: 'Materials' },
  
  // --- ENERGY: OIL, GAS & SERVICES ---
  { symbol: 'XOM', name: 'Exxon Mobil', sector: 'Energy' },
  { symbol: 'CVX', name: 'Chevron', sector: 'Energy' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy' },
  { symbol: 'OXY', name: 'Occidental', sector: 'Energy' },
  { symbol: 'HES', name: 'Hess', sector: 'Energy' },
  { symbol: 'DVN', name: 'Devon Energy', sector: 'Energy' },
  { symbol: 'FANG', name: 'Diamondback', sector: 'Energy' },
  { symbol: 'MRO', name: 'Marathon Oil', sector: 'Energy' },
  { symbol: 'CTRA', name: 'Coterra', sector: 'Energy' },
  { symbol: 'EQT', name: 'EQT Corp', sector: 'Energy' },
  { symbol: 'SLB', name: 'Schlumberger', sector: 'Energy' },
  { symbol: 'HAL', name: 'Halliburton', sector: 'Energy' },
  { symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy' },
  { symbol: 'MPC', name: 'Marathon Petro', sector: 'Energy' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { symbol: 'VLO', name: 'Valero', sector: 'Energy' },
  { symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy' },
  { symbol: 'WMB', name: 'Williams Cos', sector: 'Energy' },
  { symbol: 'OKE', name: 'ONEOK', sector: 'Energy' },
  { symbol: 'TRP', name: 'TC Energy', sector: 'Energy' },
  { symbol: 'ENB', name: 'Enbridge', sector: 'Energy' },
  { symbol: 'EPD', name: 'Enterprise', sector: 'Energy' },
  { symbol: 'MPLX', name: 'MPLX LP', sector: 'Energy' },
  
  // --- ETFS & INDICES ---
  { symbol: 'SPY', name: 'S&P 500 ETF', sector: 'ETF' },
  { symbol: 'QQQ', name: 'Nasdaq 100 ETF', sector: 'ETF' },
  { symbol: 'IWM', name: 'Russell 2000', sector: 'ETF' },
  { symbol: 'DIA', name: 'Dow Jones ETF', sector: 'ETF' },
  { symbol: 'VTI', name: 'Total Stock Mkt', sector: 'ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P', sector: 'ETF' },
  { symbol: 'IVV', name: 'Core S&P 500', sector: 'ETF' },
  { symbol: 'RSP', name: 'Equal Weight S&P', sector: 'ETF' },
  { symbol: 'XLK', name: 'Technology ETF', sector: 'ETF' },
  { symbol: 'XLF', name: 'Financial ETF', sector: 'ETF' },
  { symbol: 'XLV', name: 'Healthcare ETF', sector: 'ETF' },
  { symbol: 'XLE', name: 'Energy ETF', sector: 'ETF' },
  { symbol: 'XLC', name: 'Comm Services ETF', sector: 'ETF' },
  { symbol: 'XLY', name: 'Cons Discret ETF', sector: 'ETF' },
  { symbol: 'XLP', name: 'Cons Staples ETF', sector: 'ETF' },
  { symbol: 'XLI', name: 'Industrial ETF', sector: 'ETF' },
  { symbol: 'XLB', name: 'Materials ETF', sector: 'ETF' },
  { symbol: 'XLU', name: 'Utilities ETF', sector: 'ETF' },
  { symbol: 'XLRE', name: 'Real Estate ETF', sector: 'ETF' },
  { symbol: 'SMH', name: 'Semiconductor ETF', sector: 'ETF' },
  { symbol: 'SOXX', name: 'iShares Semi', sector: 'ETF' },
  { symbol: 'XBI', name: 'Biotech ETF', sector: 'ETF' },
  { symbol: 'IBB', name: 'iShares Biotech', sector: 'ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation', sector: 'ETF' },
  { symbol: 'ARKG', name: 'ARK Genomic', sector: 'ETF' },
  { symbol: 'ARBF', name: 'ARK Fintech', sector: 'ETF' },
  { symbol: 'ARKW', name: 'ARK Next Gen', sector: 'ETF' },
  { symbol: 'TQQQ', name: 'ProShares UltraPro QQQ', sector: 'ETF' },
  { symbol: 'SQQQ', name: 'ProShares UltraPro Short', sector: 'ETF' },
  { symbol: 'SOXL', name: 'Semi Bull 3x', sector: 'ETF' },
  { symbol: 'SOXS', name: 'Semi Bear 3x', sector: 'ETF' },
  { symbol: 'SPXL', name: 'S&P 500 Bull 3x', sector: 'ETF' },
  { symbol: 'SPXS', name: 'S&P 500 Bear 3x', sector: 'ETF' },
  { symbol: 'LABU', name: 'Biotech Bull 3x', sector: 'ETF' },
  { symbol: 'LABD', name: 'Biotech Bear 3x', sector: 'ETF' },
  { symbol: 'TNA', name: 'Small Cap Bull 3x', sector: 'ETF' },
  { symbol: 'TZA', name: 'Small Cap Bear 3x', sector: 'ETF' },
  { symbol: 'TLT', name: '20+ Year Treasury', sector: 'ETF' },
  { symbol: 'HYG', name: 'High Yield Bond', sector: 'ETF' },
  { symbol: 'LQD', name: 'Inv Grade Bond', sector: 'ETF' },
  { symbol: 'AGG', name: 'Aggregate Bond', sector: 'ETF' },
  { symbol: 'GLD', name: 'SPDR Gold', sector: 'ETF' },
  { symbol: 'IAU', name: 'iShares Gold', sector: 'ETF' },
  { symbol: 'SLV', name: 'Silver Trust', sector: 'ETF' },
  { symbol: 'USO', name: 'US Oil Fund', sector: 'ETF' },
  { symbol: 'UNG', name: 'US Gas Fund', sector: 'ETF' },
  { symbol: 'DBC', name: 'Commodity Index', sector: 'ETF' },
  { symbol: 'UUP', name: 'US Dollar Bull', sector: 'ETF' },
  { symbol: 'FXE', name: 'Euro Trust', sector: 'ETF' },
  { symbol: 'FXY', name: 'Yen Trust', sector: 'ETF' },
  { symbol: 'EEM', name: 'Emerging Mkts', sector: 'ETF' },
  { symbol: 'EFA', name: 'EAFE Index', sector: 'ETF' },
  { symbol: 'FXI', name: 'China Large-Cap', sector: 'ETF' },
  { symbol: 'KWEB', name: 'China Internet', sector: 'ETF' },
  { symbol: 'EWZ', name: 'Brazil Capped', sector: 'ETF' },
  { symbol: 'RSX', name: 'Russia', sector: 'ETF' },
  { symbol: 'INDA', name: 'MSCI India', sector: 'ETF' },
  { symbol: 'EWJ', name: 'MSCI Japan', sector: 'ETF' },
  { symbol: 'VGK', name: 'FTSE Europe', sector: 'ETF' },
  { symbol: 'EZU', name: 'MSCI Eurozone', sector: 'ETF' },
  { symbol: 'NVDL', name: 'GraniteShares 2x NVDA', sector: 'ETF' },
  { symbol: 'CONL', name: 'GraniteShares 2x COIN', sector: 'ETF' },
  { symbol: 'MSTX', name: 'Defiance 1.75x MSTR', sector: 'ETF' },
  { symbol: 'BITX', name: '2x Bitcoin Strategy', sector: 'ETF' },
  { symbol: 'IGV', name: 'Tech-Software', sector: 'ETF' },
  { symbol: 'IEF', name: '7-10 Year Treasury', sector: 'ETF' },
  { symbol: 'SHY', name: '1-3 Year Treasury', sector: 'ETF' },
  { symbol: 'URA', name: 'Global Uranium', sector: 'ETF' },
  { symbol: 'TAN', name: 'Solar ETF', sector: 'ETF' },
  { symbol: 'JETS', name: 'Jets ETF', sector: 'ETF' },
  { symbol: 'GDX', name: 'Gold Miners', sector: 'ETF' },
  { symbol: 'GDXJ', name: 'Junior Miners', sector: 'ETF' }
  { symbol: 'GRNY', name: 'Granny Shots', sector: 'ETF' }

// --- 200 UNIQUE MOMENTUM STOCKS (NOT IN YOUR ORIGINAL LIST) ---
  { symbol: 'LUMN', name: 'Lumen Technologies', sector: 'Technology' },
  { symbol: 'HIMS', name: 'Hims & Hers Health', sector: 'Healthcare' },
  { symbol: 'KVUE', name: 'Kenvue', sector: 'Consumer Defensive' },
  { symbol: 'SMR', name: 'NuScale Power', sector: 'Energy' },
  { symbol: 'TEM', name: 'Tempus AI', sector: 'Healthcare' },
  { symbol: 'WOLF', name: 'Wolfspeed', sector: 'Technology' },
  { symbol: 'ZBIT', name: 'Zenith Bio', sector: 'Healthcare' },
  { symbol: 'ALT', name: 'Altimmune', sector: 'Healthcare' },
  { symbol: 'CYTK', name: 'Cytokinetics', sector: 'Healthcare' },
  { symbol: 'AMAM', name: 'Ambrx Biopharma', sector: 'Healthcare' },
  { symbol: 'SRPT', name: 'Sarepta Therapeutics', sector: 'Healthcare' },
  { symbol: 'IONS', name: 'Ionis Pharma', sector: 'Healthcare' },
  { symbol: 'SAGE', name: 'Sage Therapeutics', sector: 'Healthcare' },
  { symbol: 'SG', name: 'Sweetgreen', sector: 'Consumer Cyclical' },
  { symbol: 'WING', name: 'Wingstop', sector: 'Consumer Cyclical' },
  { symbol: 'LOCO', name: 'El Pollo Loco', sector: 'Consumer Cyclical' },
  { symbol: 'ONON', name: 'On Holding', sector: 'Consumer Cyclical' },
  { symbol: 'BIRK', name: 'Birkenstock', sector: 'Consumer Cyclical' },
  { symbol: 'SKX', name: 'Skechers USA', sector: 'Consumer Cyclical' },
  { symbol: 'DECK', name: 'Deckers Outdoor', sector: 'Consumer Cyclical' },
  { symbol: 'CROX', name: 'Crocs', sector: 'Consumer Cyclical' },
  { symbol: 'BOOT', name: 'Boot Barn', sector: 'Consumer Cyclical' },
  { symbol: 'RVLV', name: 'Revolve Group', sector: 'Consumer Cyclical' },
  { symbol: 'FIGS', name: 'FIGS Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'AEO', name: 'American Eagle', sector: 'Consumer Cyclical' },
  { symbol: 'ANF', name: 'Abercrombie & Fitch', sector: 'Consumer Cyclical' },
  { symbol: 'GAP', name: 'The Gap', sector: 'Consumer Cyclical' },
  { symbol: 'JWN', name: 'Nordstrom', sector: 'Consumer Cyclical' },
  { symbol: 'M', name: 'Macys', sector: 'Consumer Cyclical' },
  { symbol: 'KSS', name: 'Kohls', sector: 'Consumer Cyclical' },
  { symbol: 'PLCE', name: 'Childrens Place', sector: 'Consumer Cyclical' },
  { symbol: 'RH', name: 'RH (Restoration Hardware)', sector: 'Consumer Cyclical' },
  { symbol: 'W', name: 'Wayfair', sector: 'Consumer Cyclical' },
  { symbol: 'CVNA', name: 'Carvana', sector: 'Consumer Cyclical' },
  { symbol: 'Vroom', name: 'Vroom Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'OPEN', name: 'Opendoor Technologies', sector: 'Real Estate' },
  { symbol: 'RDFN', name: 'Redfin', sector: 'Real Estate' },
  { symbol: 'Z', name: 'Zillow Group', sector: 'Real Estate' },
  { symbol: 'COMP', name: 'Compass Inc.', sector: 'Real Estate' },
  { symbol: 'EXPI', name: 'eXp World Holdings', sector: 'Real Estate' },
  { symbol: 'UPST', name: 'Upstart Holdings', sector: 'Financial' },
  { symbol: 'NU', name: 'Nu Holdings', sector: 'Financial' },
  { symbol: 'PAGS', name: 'PagSeguro Digital', sector: 'Financial' },
  { symbol: 'STNE', name: 'StoneCo', sector: 'Financial' },
  { symbol: 'MELI', name: 'MercadoLibre', sector: 'Consumer Cyclical' },
  { symbol: 'SE', name: 'Sea Limited', sector: 'Consumer Cyclical' },
  { symbol: 'PDD', name: 'PDD Holdings', sector: 'Consumer Cyclical' },
  { symbol: 'TME', name: 'Tencent Music', sector: 'Communication' },
  { symbol: 'IQ', name: 'iQIYI', sector: 'Communication' },
  { symbol: 'BILI', name: 'Bilibili', sector: 'Communication' },
  { symbol: 'DASH', name: 'DoorDash', sector: 'Technology' },
  { symbol: 'LYFT', name: 'Lyft Inc.', sector: 'Technology' },
  { symbol: 'GRUB', name: 'Grubhub', sector: 'Technology' },
  { symbol: 'ABNB', name: 'Airbnb', sector: 'Consumer Cyclical' },
  { symbol: 'EXPE', name: 'Expedia Group', sector: 'Consumer Cyclical' },
  { symbol: 'TRIP', name: 'TripAdvisor', sector: 'Consumer Cyclical' },
  { symbol: 'TNL', name: 'Travel + Leisure', sector: 'Consumer Cyclical' },
  { symbol: 'CCL', name: 'Carnival Corp', sector: 'Consumer Cyclical' },
  { symbol: 'NCLH', name: 'Norwegian Cruise', sector: 'Consumer Cyclical' },
  { symbol: 'PENN', name: 'Penn Entertainment', sector: 'Consumer Cyclical' },
  { symbol: 'GEN', name: 'Gen Digital', sector: 'Technology' },
  { symbol: 'NLOK', name: 'NortonLifeLock', sector: 'Technology' },
  { symbol: 'S', name: 'SentinelOne', sector: 'Technology' },
  { symbol: 'FORG', name: 'ForgeRock', sector: 'Technology' },
  { symbol: 'PING', name: 'Ping Identity', sector: 'Technology' },
  { symbol: 'MGNI', name: 'Magnite', sector: 'Technology' },
  { symbol: 'PUBM', name: 'PubMatic', sector: 'Technology' },
  { symbol: 'PERI', name: 'Perion Network', sector: 'Technology' },
  { symbol: 'RING', name: 'RingCentral', sector: 'Technology' },
  { symbol: 'EGHT', name: '8x8 Inc.', sector: 'Technology' },
  { symbol: 'AKAM', name: 'Akamai Tech', sector: 'Technology' },
  { symbol: 'LLNW', name: 'Limelight Networks', sector: 'Technology' },
  { symbol: 'BIGC', name: 'BigCommerce', sector: 'Technology' },
  { symbol: 'ETSY', name: 'Etsy Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'CHWY', name: 'Chewy Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'WWAY', name: 'Wayfair Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'PINS', name: 'Pinterest', sector: 'Communication' },
  { symbol: 'SNAP', name: 'Snap Inc.', sector: 'Communication' },
  { symbol: 'MTCH', name: 'Match Group', sector: 'Communication' },
  { symbol: 'BMBL', name: 'Bumble Inc.', sector: 'Communication' },
  { symbol: 'DUOL', name: 'Duolingo', sector: 'Technology' },
  { symbol: 'COUR', name: 'Coursera', sector: 'Technology' },
  { symbol: 'UDMY', name: 'Udemy', sector: 'Technology' },
  { symbol: 'CHGG', name: 'Chegg', sector: 'Consumer Cyclical' },
  { symbol: 'TWOU', name: '2U Inc.', sector: 'Consumer Cyclical' },
  { symbol: 'DOCN', name: 'DigitalOcean', sector: 'Technology' },
  { symbol: 'VULC', name: 'Vulcan Materials', sector: 'Basic Materials' },
  { symbol: 'SUM', name: 'Summit Materials', sector: 'Basic Materials' },
  { symbol: 'EXP', name: 'Eagle Materials', sector: 'Basic Materials' },
  { symbol: 'RS', name: 'Reliance Steel', sector: 'Basic Materials' },
  { symbol: 'CENX', name: 'Century Aluminum', sector: 'Basic Materials' },
  { symbol: 'MP', name: 'MP Materials', sector: 'Basic Materials' },
  { symbol: 'LAC', name: 'Lithium Americas', sector: 'Basic Materials' },
  { symbol: 'LTHM', name: 'Livent Corp', sector: 'Basic Materials' },
  { symbol: 'PLL', name: 'Piedmont Lithium', sector: 'Basic Materials' },
  { symbol: 'FNV', name: 'Franco-Nevada', sector: 'Basic Materials' },
  { symbol: 'RGLD', name: 'Royal Gold', sector: 'Basic Materials' },
  { symbol: 'KGC', name: 'Kinross Gold', sector: 'Basic Materials' },
  { symbol: 'AU', name: 'AngloGold Ashanti', sector: 'Basic Materials' },
  { symbol: 'HMY', name: 'Harmony Gold', sector: 'Basic Materials' },
  { symbol: 'GFI', name: 'Gold Fields', sector: 'Basic Materials' },
  { symbol: 'PAAS', name: 'Pan American Silver', sector: 'Basic Materials' },
  { symbol: 'HL', name: 'Hecla Mining', sector: 'Basic Materials' },
  { symbol: 'CDE', name: 'Coeur Mining', sector: 'Basic Materials' },
  { symbol: 'AG', name: 'First Majestic', sector: 'Basic Materials' },
  { symbol: 'FSM', name: 'Fortuna Silver', sector: 'Basic Materials' },
  { symbol: 'EXK', name: 'Endeavour Silver', sector: 'Basic Materials' },
  { symbol: 'MAG', name: 'MAG Silver', sector: 'Basic Materials' },
  { symbol: 'SILV', name: 'SilverCrest Metals', sector: 'Basic Materials' },
  { symbol: 'SVM', name: 'Silvercorp Metals', sector: 'Basic Materials' },
  { symbol: 'SAND', name: 'Sandstorm Gold', sector: 'Basic Materials' },
  { symbol: 'OR', name: 'Osisko Gold', sector: 'Basic Materials' },
  { symbol: 'TFPM', name: 'Triple Flag', sector: 'Basic Materials' },
  { symbol: 'WPM', name: 'Wheaton Precious', sector: 'Basic Materials' },
  { symbol: 'NTR', name: 'Nutrien Ltd', sector: 'Basic Materials' },
  { symbol: 'ICL', name: 'ICL Group', sector: 'Basic Materials' },
  { symbol: 'ANET', name: 'Arista Networks', sector: 'Technology' },
  { symbol: 'ASML', name: 'ASML Holding', sector: 'Technology' },

];

