
export const POPULAR_STOCKS = [
  // --- USER REQUESTED & TRENDING ---
  { symbol: 'CRCL', name: 'CRCL', sector: 'Technology' },
  { symbol: 'CRWV', name: 'CRWV', sector: 'Technology' },
  { symbol: 'OKLO', name: 'Oklo Inc', sector: 'Energy' },
  { symbol: 'OSCR', name: 'Oscar Health', sector: 'Healthcare' },
  { symbol: 'NNE', name: 'Nano Nuclear Energy', sector: 'Energy' },
  { symbol: 'RDDT', name: 'Reddit', sector: 'Technology' },
  { symbol: 'SMR', name: 'NuScale Power', sector: 'Energy' },
  { symbol: 'DJT', name: 'Trump Media', sector: 'Communication Services' },
  { symbol: 'SMCI', name: 'Super Micro Computer', sector: 'Technology' },
  { symbol: 'ARM', name: 'Arm Holdings', sector: 'Technology' },
  { symbol: 'CART', name: 'Instacart', sector: 'Technology' },
  { symbol: 'KVUE', name: 'Kenvue', sector: 'Consumer Defensive' },
  { symbol: 'CAVA', name: 'CAVA Group', sector: 'Consumer Cyclical' },
  { symbol: 'SG', name: 'Sweetgreen', sector: 'Consumer Cyclical' },
  { symbol: 'VKTX', name: 'Viking Therapeutics', sector: 'Healthcare' },
  { symbol: 'SOUN', name: 'SoundHound AI', sector: 'Technology' },
  { symbol: 'BBAI', name: 'BigBear.ai', sector: 'Technology' },
  { symbol: 'NU', name: 'Nu Holdings', sector: 'Financial' },
  { symbol: 'MNDY', name: 'Monday.com', sector: 'Technology' },

  // --- MAGNIFICENT 7 & MEGA CAP ---
  { symbol: 'NVDA', name: 'NVIDIA Corp', sector: 'Technology' },
  { symbol: 'MSFT', name: 'Microsoft Corp', sector: 'Technology' },
  { symbol: 'AAPL', name: 'Apple Inc', sector: 'Technology' },
  { symbol: 'GOOGL', name: 'Alphabet Inc (A)', sector: 'Technology' },
  { symbol: 'GOOG', name: 'Alphabet Inc (C)', sector: 'Technology' },
  { symbol: 'AMZN', name: 'Amazon.com Inc', sector: 'Consumer Cyclical' },
  { symbol: 'META', name: 'Meta Platforms', sector: 'Communication Services' },
  { symbol: 'TSLA', name: 'Tesla Inc', sector: 'Consumer Cyclical' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway', sector: 'Financial' },
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Healthcare' },
  { symbol: 'AVGO', name: 'Broadcom Inc', sector: 'Technology' },
  { symbol: 'V', name: 'Visa Inc', sector: 'Financial' },
  { symbol: 'JPM', name: 'JPMorgan Chase', sector: 'Financial' },
  { symbol: 'WMT', name: 'Walmart Inc', sector: 'Consumer Defensive' },
  { symbol: 'XOM', name: 'Exxon Mobil', sector: 'Energy' },
  { symbol: 'MA', name: 'Mastercard', sector: 'Financial' },
  { symbol: 'UNH', name: 'UnitedHealth Group', sector: 'Healthcare' },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer Defensive' },
  { symbol: 'COST', name: 'Costco Wholesale', sector: 'Consumer Defensive' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare' },
  { symbol: 'HD', name: 'Home Depot', sector: 'Consumer Cyclical' },
  { symbol: 'MRK', name: 'Merck & Co', sector: 'Healthcare' },
  { symbol: 'ORCL', name: 'Oracle Corp', sector: 'Technology' },
  { symbol: 'CVX', name: 'Chevron Corp', sector: 'Energy' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Financial' },
  { symbol: 'KO', name: 'Coca-Cola', sector: 'Consumer Defensive' },
  { symbol: 'NFLX', name: 'Netflix', sector: 'Communication Services' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Consumer Defensive' },
  { symbol: 'CRM', name: 'Salesforce', sector: 'Technology' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology' },
  { symbol: 'ADBE', name: 'Adobe Inc', sector: 'Technology' },
  { symbol: 'LIN', name: 'Linde plc', sector: 'Basic Materials' },
  { symbol: 'TMO', name: 'Thermo Fisher', sector: 'Healthcare' },
  { symbol: 'ACN', name: 'Accenture', sector: 'Technology' },
  { symbol: 'MCD', name: 'McDonald\'s', sector: 'Consumer Cyclical' },
  { symbol: 'DIS', name: 'Walt Disney', sector: 'Communication Services' },
  { symbol: 'CSCO', name: 'Cisco Systems', sector: 'Technology' },
  { symbol: 'ABT', name: 'Abbott Labs', sector: 'Healthcare' },
  { symbol: 'TMUS', name: 'T-Mobile US', sector: 'Communication Services' },
  { symbol: 'DHR', name: 'Danaher Corp', sector: 'Healthcare' },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Financial' },
  { symbol: 'INTU', name: 'Intuit', sector: 'Technology' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Technology' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Communication Services' },
  { symbol: 'IBM', name: 'IBM', sector: 'Technology' },
  { symbol: 'CAT', name: 'Caterpillar', sector: 'Industrials' },
  { symbol: 'GE', name: 'General Electric', sector: 'Industrials' },
  { symbol: 'INTC', name: 'Intel Corp', sector: 'Technology' },
  { symbol: 'AMGN', name: 'Amgen', sector: 'Healthcare' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
  { symbol: 'NOW', name: 'ServiceNow', sector: 'Technology' },
  { symbol: 'SPGI', name: 'S&P Global', sector: 'Financial' },
  { symbol: 'AXP', name: 'American Express', sector: 'Financial' },
  { symbol: 'PM', name: 'Philip Morris', sector: 'Consumer Defensive' },
  { symbol: 'UBER', name: 'Uber Technologies', sector: 'Technology' },
  { symbol: 'UNP', name: 'Union Pacific', sector: 'Industrials' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Healthcare' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Financial' },
  { symbol: 'RTX', name: 'RTX Corp', sector: 'Industrials' },
  { symbol: 'HON', name: 'Honeywell', sector: 'Industrials' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
  { symbol: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Cyclical' },
  { symbol: 'T', name: 'AT&T', sector: 'Communication Services' },
  { symbol: 'LOW', name: 'Lowe\'s', sector: 'Consumer Cyclical' },
  { symbol: 'ELV', name: 'Elevance Health', sector: 'Healthcare' },
  { symbol: 'SYK', name: 'Stryker', sector: 'Healthcare' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financial' },
  { symbol: 'BLK', name: 'BlackRock', sector: 'Financial' },
  { symbol: 'ETN', name: 'Eaton Corp', sector: 'Industrials' },
  { symbol: 'TJX', name: 'TJX Companies', sector: 'Consumer Cyclical' },
  { symbol: 'UPS', name: 'UPS', sector: 'Industrials' },
  { symbol: 'PGR', name: 'Progressive', sector: 'Financial' },
  { symbol: 'C', name: 'Citigroup', sector: 'Financial' },
  { symbol: 'VRTX', name: 'Vertex Pharma', sector: 'Healthcare' },
  { symbol: 'BA', name: 'Boeing', sector: 'Industrials' },
  { symbol: 'REGN', name: 'Regeneron', sector: 'Healthcare' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Technology' },
  { symbol: 'CB', name: 'Chubb Ltd', sector: 'Financial' },
  { symbol: 'PLD', name: 'Prologis', sector: 'Real Estate' },
  { symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Financial' },
  { symbol: 'ADP', name: 'ADP', sector: 'Industrials' },
  { symbol: 'BSX', name: 'Boston Scientific', sector: 'Healthcare' },
  { symbol: 'AMT', name: 'American Tower', sector: 'Real Estate' },
  { symbol: 'MDT', name: 'Medtronic', sector: 'Healthcare' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Technology' },
  { symbol: 'KLAC', name: 'KLA Corp', sector: 'Technology' },
  { symbol: 'DE', name: 'Deere & Co', sector: 'Industrials' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer Cyclical' },
  { symbol: 'CI', name: 'Cigna', sector: 'Healthcare' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Healthcare' },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrials' },
  { symbol: 'MU', name: 'Micron Technology', sector: 'Technology' },
  { symbol: 'SNPS', name: 'Synopsys', sector: 'Technology' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare' },
  { symbol: 'MDLZ', name: 'Mondelez', sector: 'Consumer Defensive' },
  { symbol: 'ADI', name: 'Analog Devices', sector: 'Technology' },
  { symbol: 'FI', name: 'Fiserv', sector: 'Technology' },
  { symbol: 'CDNS', name: 'Cadence Design', sector: 'Technology' },
  { symbol: 'MO', name: 'Altria Group', sector: 'Consumer Defensive' },
  { symbol: 'CVS', name: 'CVS Health', sector: 'Healthcare' },
  { symbol: 'SO', name: 'Southern Company', sector: 'Utilities' },
  { symbol: 'HCA', name: 'HCA Healthcare', sector: 'Healthcare' },
  { symbol: 'ZTS', name: 'Zoetis', sector: 'Healthcare' },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities' },
  { symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Basic Materials' },
  { symbol: 'EQIX', name: 'Equinix', sector: 'Real Estate' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Financial' },
  { symbol: 'SLB', name: 'Schlumberger', sector: 'Energy' },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy' },
  { symbol: 'CME', name: 'CME Group', sector: 'Financial' },
  { symbol: 'WM', name: 'Waste Management', sector: 'Industrials' },
  { symbol: 'ITW', name: 'Illinois Tool Works', sector: 'Industrials' },
  { symbol: 'CSX', name: 'CSX Corp', sector: 'Industrials' },
  { symbol: 'MCK', name: 'McKesson', sector: 'Healthcare' },
  { symbol: 'NKE', name: 'Nike', sector: 'Consumer Cyclical' },
  { symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer Defensive' },
  { symbol: 'BDX', name: 'Becton Dickinson', sector: 'Healthcare' },
  { symbol: 'PH', name: 'Parker-Hannifin', sector: 'Industrials' },
  { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy' },
  { symbol: 'USB', name: 'US Bancorp', sector: 'Financial' },
  { symbol: 'PYPL', name: 'PayPal', sector: 'Financial' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { symbol: 'TT', name: 'Trane Technologies', sector: 'Industrials' },
  { symbol: 'ORLY', name: 'O\'Reilly Automotive', sector: 'Consumer Cyclical' },
  { symbol: 'EMR', name: 'Emerson Electric', sector: 'Industrials' },
  { symbol: 'MAR', name: 'Marriott', sector: 'Consumer Cyclical' },
  { symbol: 'APH', name: 'Amphenol', sector: 'Technology' },
  { symbol: 'TDG', name: 'TransDigm', sector: 'Industrials' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', sector: 'Technology' },
  { symbol: 'GD', name: 'General Dynamics', sector: 'Industrials' },
  { symbol: 'PNC', name: 'PNC Financial', sector: 'Financial' },
  { symbol: 'ADSK', name: 'Autodesk', sector: 'Technology' },
  { symbol: 'FCX', name: 'Freeport-McMoRan', sector: 'Basic Materials' },
  { symbol: 'ROP', name: 'Roper Technologies', sector: 'Technology' },
  { symbol: 'MCO', name: 'Moody\'s', sector: 'Financial' },
  { symbol: 'PCAR', name: 'PACCAR', sector: 'Industrials' },
  { symbol: 'MSI', name: 'Motorola Solutions', sector: 'Technology' },
  { symbol: 'CTAS', name: 'Cintas', sector: 'Industrials' },
  { symbol: 'FDX', name: 'FedEx', sector: 'Industrials' },
  { symbol: 'GM', name: 'General Motors', sector: 'Consumer Cyclical' },
  { symbol: 'NSC', name: 'Norfolk Southern', sector: 'Industrials' },
  { symbol: 'WELL', name: 'Welltower', sector: 'Real Estate' },
  { symbol: 'ECL', name: 'Ecolab', sector: 'Basic Materials' },
  { symbol: 'COF', name: 'Capital One', sector: 'Financial' },
  { symbol: 'WMB', name: 'Williams Companies', sector: 'Energy' },
  { symbol: 'SPG', name: 'Simon Property', sector: 'Real Estate' },
  { symbol: 'EW', name: 'Edwards Lifesciences', sector: 'Healthcare' },
  { symbol: 'HLT', name: 'Hilton', sector: 'Consumer Cyclical' },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy' },
  { symbol: 'AON', name: 'Aon plc', sector: 'Financial' },
  { symbol: 'DXCM', name: 'Dexcom', sector: 'Healthcare' },
  { symbol: 'MMM', name: '3M', sector: 'Industrials' },
  { symbol: 'F', name: 'Ford Motor', sector: 'Consumer Cyclical' },
  { symbol: 'AIG', name: 'AIG', sector: 'Financial' },
  { symbol: 'KMB', name: 'Kimberly-Clark', sector: 'Consumer Defensive' },
  { symbol: 'CARR', name: 'Carrier Global', sector: 'Industrials' },
  { symbol: 'TRV', name: 'Travelers', sector: 'Financial' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher', sector: 'Financial' },
  { symbol: 'DLR', name: 'Digital Realty', sector: 'Real Estate' },
  { symbol: 'MET', name: 'MetLife', sector: 'Financial' },
  { symbol: 'TGT', name: 'Target', sector: 'Consumer Defensive' },
  { symbol: 'BK', name: 'BNY Mellon', sector: 'Financial' },
  { symbol: 'MNST', name: 'Monster Beverage', sector: 'Consumer Defensive' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate' },
  { symbol: 'NOC', name: 'Northrop Grumman', sector: 'Industrials' },
  { symbol: 'SRE', name: 'Sempra', sector: 'Utilities' },
  { symbol: 'AFL', name: 'Aflac', sector: 'Financial' },
  { symbol: 'STZ', name: 'Constellation Brands', sector: 'Consumer Defensive' },
  { symbol: 'HES', name: 'Hess Corp', sector: 'Energy' },
  { symbol: 'VLO', name: 'Valero Energy', sector: 'Energy' },
  { symbol: 'O', name: 'Realty Income', sector: 'Real Estate' },
  { symbol: 'ALL', name: 'Allstate', sector: 'Financial' },
  { symbol: 'D', name: 'Dominion Energy', sector: 'Utilities' },
  { symbol: 'KMI', name: 'Kinder Morgan', sector: 'Energy' },
  { symbol: 'AZN', name: 'AstraZeneca', sector: 'Healthcare' },
  { symbol: 'LULU', name: 'Lululemon', sector: 'Consumer Cyclical' },
  { symbol: 'MRNA', name: 'Moderna', sector: 'Healthcare' },
  { symbol: 'TEAM', name: 'Atlassian', sector: 'Technology' },
  { symbol: 'WDAY', name: 'Workday', sector: 'Technology' },
  { symbol: 'CRWD', name: 'CrowdStrike', sector: 'Technology' },
  { symbol: 'ABNB', name: 'Airbnb', sector: 'Consumer Cyclical' },
  { symbol: 'DASH', name: 'DoorDash', sector: 'Consumer Cyclical' },
  { symbol: 'HOOD', name: 'Robinhood', sector: 'Financial' },
  { symbol: 'COIN', name: 'Coinbase', sector: 'Financial' },
  { symbol: 'PLTR', name: 'Palantir', sector: 'Technology' },
  { symbol: 'SNOW', name: 'Snowflake', sector: 'Technology' },
  { symbol: 'ROKU', name: 'Roku', sector: 'Communication Services' },
  { symbol: 'SQ', name: 'Block (Square)', sector: 'Financial' },
  { symbol: 'SHOP', name: 'Shopify', sector: 'Technology' },
  { symbol: 'TTD', name: 'The Trade Desk', sector: 'Technology' },
  { symbol: 'NET', name: 'Cloudflare', sector: 'Technology' },
  { symbol: 'MDB', name: 'MongoDB', sector: 'Technology' },
  { symbol: 'ZS', name: 'Zscaler', sector: 'Technology' },
  { symbol: 'DKNG', name: 'DraftKings', sector: 'Consumer Cyclical' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery', sector: 'Communication Services' },
  { symbol: 'GEHC', name: 'GE HealthCare', sector: 'Healthcare' },
  { symbol: 'CEG', name: 'Constellation Energy', sector: 'Utilities' },
  { symbol: 'KKR', name: 'KKR & Co', sector: 'Financial' },
  
  // --- TECH, SOFTWARE & CYBERSECURITY ---
  { symbol: 'DDOG', name: 'Datadog', sector: 'Technology' },
  { symbol: 'HUBS', name: 'HubSpot', sector: 'Technology' },
  { symbol: 'APP', name: 'AppLovin', sector: 'Technology' },
  { symbol: 'PATH', name: 'UiPath', sector: 'Technology' },
  { symbol: 'U', name: 'Unity Software', sector: 'Technology' },
  { symbol: 'AFRM', name: 'Affirm', sector: 'Financial' },
  { symbol: 'UPST', name: 'Upstart', sector: 'Financial' },
  { symbol: 'CVNA', name: 'Carvana', sector: 'Consumer Cyclical' },
  { symbol: 'GTLB', name: 'GitLab', sector: 'Technology' },
  { symbol: 'HCP', name: 'HashiCorp', sector: 'Technology' },
  { symbol: 'CFLT', name: 'Confluent', sector: 'Technology' },
  { symbol: 'IOT', name: 'Samsara', sector: 'Technology' },
  { symbol: 'OKTA', name: 'Okta', sector: 'Technology' },
  { symbol: 'DOCU', name: 'DocuSign', sector: 'Technology' },
  { symbol: 'FSLY', name: 'Fastly', sector: 'Technology' },
  { symbol: 'TWLO', name: 'Twilio', sector: 'Technology' },
  { symbol: 'RBLX', name: 'Roblox', sector: 'Technology' },
  { symbol: 'MSTR', name: 'MicroStrategy', sector: 'Technology' },
  { symbol: 'S', name: 'SentinelOne', sector: 'Technology' },
  { symbol: 'CYBR', name: 'CyberArk', sector: 'Technology' },
  { symbol: 'TENB', name: 'Tenable', sector: 'Technology' },
  { symbol: 'QLYS', name: 'Qualys', sector: 'Technology' },
  { symbol: 'VRNS', name: 'Varonis', sector: 'Technology' },
  { symbol: 'FTNT', name: 'Fortinet', sector: 'Technology' },
  { symbol: 'GEN', name: 'Gen Digital', sector: 'Technology' },
  
  // --- SEMICONDUCTORS & HARDWARE ---
  { symbol: 'WOLF', name: 'Wolfspeed', sector: 'Technology' },
  { symbol: 'LSCC', name: 'Lattice Semi', sector: 'Technology' },
  { symbol: 'RMBS', name: 'Rambus', sector: 'Technology' },
  { symbol: 'SGH', name: 'SMART Global', sector: 'Technology' },
  { symbol: 'POWI', name: 'Power Integrations', sector: 'Technology' },
  { symbol: 'DIOD', name: 'Diodes Inc', sector: 'Technology' },
  { symbol: 'SLAB', name: 'Silicon Labs', sector: 'Technology' },
  { symbol: 'CRUS', name: 'Cirrus Logic', sector: 'Technology' },
  { symbol: 'FORM', name: 'FormFactor', sector: 'Technology' },
  { symbol: 'AOSL', name: 'Alpha and Omega', sector: 'Technology' },
  { symbol: 'MXL', name: 'MaxLinear', sector: 'Technology' },
  { symbol: 'ONTO', name: 'Onto Innovation', sector: 'Technology' },
  { symbol: 'CAMT', name: 'Camtek', sector: 'Technology' },
  { symbol: 'ACLS', name: 'Axcelis', sector: 'Technology' },
  { symbol: 'VECO', name: 'Veeco', sector: 'Technology' },
  { symbol: 'AEHR', name: 'Aehr Test Systems', sector: 'Technology' },
  { symbol: 'INDI', name: 'indie Semiconductor', sector: 'Technology' },
  
  // --- HEALTHCARE, BIOTECH & PHARMA ---
  { symbol: 'VTRS', name: 'Viatris', sector: 'Healthcare' },
  { symbol: 'TEVA', name: 'Teva Pharma', sector: 'Healthcare' },
  { symbol: 'BHC', name: 'Bausch Health', sector: 'Healthcare' },
  { symbol: 'CTLT', name: 'Catalent', sector: 'Healthcare' },
  { symbol: 'TECH', name: 'Bio-Techne', sector: 'Healthcare' },
  { symbol: 'WST', name: 'West Pharma', sector: 'Healthcare' },
  { symbol: 'RGEN', name: 'Repligen', sector: 'Healthcare' },
  { symbol: 'TXG', name: '10x Genomics', sector: 'Healthcare' },
  { symbol: 'PACB', name: 'Pacific Biosciences', sector: 'Healthcare' },
  { symbol: 'NTRA', name: 'Natera', sector: 'Healthcare' },
  { symbol: 'GH', name: 'Guardant Health', sector: 'Healthcare' },
  { symbol: 'EXAS', name: 'Exact Sciences', sector: 'Healthcare' },
  { symbol: 'PODD', name: 'Insulet', sector: 'Healthcare' },
  { symbol: 'TNDM', name: 'Tandem Diabetes', sector: 'Healthcare' },
  { symbol: 'VEEV', name: 'Veeva Systems', sector: 'Healthcare' },
  { symbol: 'PEN', name: 'Penumbra', sector: 'Healthcare' },
  { symbol: 'GMED', name: 'Globus Medical', sector: 'Healthcare' },
  { symbol: 'HIMS', name: 'Hims & Hers', sector: 'Healthcare' },
  { symbol: 'ALGN', name: 'Align Tech', sector: 'Healthcare' },
  { symbol: 'XRAY', name: 'Dentsply Sirona', sector: 'Healthcare' },
  { symbol: 'RVTY', name: 'Revvity', sector: 'Healthcare' },
  
  // --- CONSUMER, RETAIL & APPAREL ---
  { symbol: 'CROX', name: 'Crocs', sector: 'Consumer Cyclical' },
  { symbol: 'DECK', name: 'Deckers Outdoor', sector: 'Consumer Cyclical' },
  { symbol: 'SKX', name: 'Skechers', sector: 'Consumer Cyclical' },
  { symbol: 'BIRK', name: 'Birkenstock', sector: 'Consumer Cyclical' },
  { symbol: 'ONON', name: 'On Holding', sector: 'Consumer Cyclical' },
  { symbol: 'BOOT', name: 'Boot Barn', sector: 'Consumer Cyclical' },
  { symbol: 'GPS', name: 'Gap Inc', sector: 'Consumer Cyclical' },
  { symbol: 'ANF', name: 'Abercrombie & Fitch', sector: 'Consumer Cyclical' },
  { symbol: 'AEO', name: 'American Eagle', sector: 'Consumer Cyclical' },
  { symbol: 'URBN', name: 'Urban Outfitters', sector: 'Consumer Cyclical' },
  { symbol: 'BURL', name: 'Burlington', sector: 'Consumer Cyclical' },
  { symbol: 'ROST', name: 'Ross Stores', sector: 'Consumer Cyclical' },
  { symbol: 'ULTA', name: 'Ulta Beauty', sector: 'Consumer Cyclical' },
  { symbol: 'ELF', name: 'e.l.f. Beauty', sector: 'Consumer Cyclical' },
  { symbol: 'COTY', name: 'Coty Inc', sector: 'Consumer Cyclical' },
  { symbol: 'IPAR', name: 'Inter Parfums', sector: 'Consumer Cyclical' },
  { symbol: 'CHWY', name: 'Chewy', sector: 'Consumer Cyclical' },
  { symbol: 'WOOF', name: 'Petco', sector: 'Consumer Cyclical' },
  
  // --- FOOD & BEVERAGE ---
  { symbol: 'CELH', name: 'Celsius Holdings', sector: 'Consumer Defensive' },
  { symbol: 'FIZZ', name: 'National Beverage', sector: 'Consumer Defensive' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper', sector: 'Consumer Defensive' },
  { symbol: 'SAM', name: 'Boston Beer', sector: 'Consumer Defensive' },
  { symbol: 'TAP', name: 'Molson Coors', sector: 'Consumer Defensive' },
  { symbol: 'BUD', name: 'Anheuser-Busch', sector: 'Consumer Defensive' },
  { symbol: 'DEO', name: 'Diageo', sector: 'Consumer Defensive' },
  { symbol: 'BF.B', name: 'Brown-Forman', sector: 'Consumer Defensive' },
  
  // --- ENERGY, SOLAR & UTILITIES ---
  { symbol: 'FSLR', name: 'First Solar', sector: 'Technology' },
  { symbol: 'ENPH', name: 'Enphase', sector: 'Technology' },
  { symbol: 'SEDG', name: 'SolarEdge', sector: 'Technology' },
  { symbol: 'RUN', name: 'Sunrun', sector: 'Technology' },
  { symbol: 'NOVA', name: 'Sunnova', sector: 'Utilities' },
  { symbol: 'JKS', name: 'JinkoSolar', sector: 'Technology' },
  { symbol: 'ARRY', name: 'Array Technologies', sector: 'Technology' },
  { symbol: 'SHLS', name: 'Shoals Technologies', sector: 'Technology' },
  { symbol: 'NXT', name: 'Nextracker', sector: 'Technology' },
  { symbol: 'TPIC', name: 'TPI Composites', sector: 'Industrials' },
  { symbol: 'BE', name: 'Bloom Energy', sector: 'Industrials' },
  { symbol: 'PLUG', name: 'Plug Power', sector: 'Industrials' },
  { symbol: 'FCEL', name: 'FuelCell Energy', sector: 'Industrials' },
  { symbol: 'BLDP', name: 'Ballard Power', sector: 'Industrials' },
  
  // --- EV, AUTO & CHARGING ---
  { symbol: 'RIVN', name: 'Rivian', sector: 'Consumer Cyclical' },
  { symbol: 'LCID', name: 'Lucid Group', sector: 'Consumer Cyclical' },
  { symbol: 'NIO', name: 'NIO Inc', sector: 'Consumer Cyclical' },
  { symbol: 'XPEV', name: 'XPeng', sector: 'Consumer Cyclical' },
  { symbol: 'LI', name: 'Li Auto', sector: 'Consumer Cyclical' },
  { symbol: 'PSNY', name: 'Polestar', sector: 'Consumer Cyclical' },
  { symbol: 'QS', name: 'QuantumScape', sector: 'Consumer Cyclical' },
  { symbol: 'CHPT', name: 'ChargePoint', sector: 'Industrials' },
  { symbol: 'EVGO', name: 'EVgo', sector: 'Utilities' },
  { symbol: 'BLNK', name: 'Blink Charging', sector: 'Industrials' },
  
  // --- SPACE & AEROSPACE ---
  { symbol: 'RKLB', name: 'Rocket Lab', sector: 'Industrials' },
  { symbol: 'SPCE', name: 'Virgin Galactic', sector: 'Industrials' },
  { symbol: 'ASTS', name: 'AST SpaceMobile', sector: 'Communication Services' },
  { symbol: 'LUNR', name: 'Intuitive Machines', sector: 'Industrials' },
  { symbol: 'PL', name: 'Planet Labs', sector: 'Technology' },
  { symbol: 'SPIR', name: 'Spire Global', sector: 'Technology' },
  { symbol: 'BKSY', name: 'BlackSky', sector: 'Technology' },
  { symbol: 'JOBY', name: 'Joby Aviation', sector: 'Industrials' },
  { symbol: 'ACHR', name: 'Archer Aviation', sector: 'Industrials' },
  { symbol: 'HII', name: 'Huntington Ingalls', sector: 'Industrials' },
  
  // --- INDUSTRIAL & MATERIALS ---
  { symbol: 'X', name: 'US Steel', sector: 'Basic Materials' },
  { symbol: 'CLF', name: 'Cleveland-Cliffs', sector: 'Basic Materials' },
  { symbol: 'NUE', name: 'Nucor', sector: 'Basic Materials' },
  { symbol: 'STLD', name: 'Steel Dynamics', sector: 'Basic Materials' },
  { symbol: 'AA', name: 'Alcoa', sector: 'Basic Materials' },
  { symbol: 'SCCO', name: 'Southern Copper', sector: 'Basic Materials' },
  { symbol: 'TECK', name: 'Teck Resources', sector: 'Basic Materials' },
  { symbol: 'RIO', name: 'Rio Tinto', sector: 'Basic Materials' },
  { symbol: 'BHP', name: 'BHP Group', sector: 'Basic Materials' },
  { symbol: 'VALE', name: 'Vale SA', sector: 'Basic Materials' },
  
  // --- FINANCIALS & FINTECH ---
  { symbol: 'SOFI', name: 'SoFi Technologies', sector: 'Financial' },
  { symbol: 'LC', name: 'LendingClub', sector: 'Financial' },
  { symbol: 'GPN', name: 'Global Payments', sector: 'Financial' },
  { symbol: 'BILL', name: 'Bill.com', sector: 'Technology' },
  { symbol: 'TOST', name: 'Toast', sector: 'Technology' },
  { symbol: 'CPAY', name: 'Corpay', sector: 'Financial' },
  { symbol: 'WEX', name: 'WEX Inc', sector: 'Financial' },
  { symbol: 'EG', name: 'Everest Group', sector: 'Financial' },
  
  // --- REAL ESTATE (REITs) ---
  { symbol: 'CCI', name: 'Crown Castle', sector: 'Real Estate' },
  { symbol: 'EXR', name: 'Extra Space', sector: 'Real Estate' },
  { symbol: 'VICI', name: 'VICI Properties', sector: 'Real Estate' },
  { symbol: 'GLPI', name: 'Gaming and Leisure', sector: 'Real Estate' },
  { symbol: 'KIM', name: 'Kimco Realty', sector: 'Real Estate' },
  { symbol: 'REG', name: 'Regency Centers', sector: 'Real Estate' },
  { symbol: 'AVB', name: 'AvalonBay', sector: 'Real Estate' },
  { symbol: 'EQR', name: 'Equity Residential', sector: 'Real Estate' },
  
  // --- CRYPTO & BLOCKCHAIN ---
  { symbol: 'MARA', name: 'Marathon Digital', sector: 'Technology' },
  { symbol: 'RIOT', name: 'Riot Platforms', sector: 'Technology' },
  { symbol: 'CLSK', name: 'CleanSpark', sector: 'Technology' },
  { symbol: 'HUT', name: 'Hut 8', sector: 'Technology' },
  { symbol: 'HIVE', name: 'HIVE Digital', sector: 'Technology' },
  { symbol: 'BITF', name: 'Bitfarms', sector: 'Technology' },
  { symbol: 'CORZ', name: 'Core Scientific', sector: 'Technology' },
  { symbol: 'CIFR', name: 'Cipher Mining', sector: 'Technology' },
  { symbol: 'IREN', name: 'Iris Energy', sector: 'Technology' },
  { symbol: 'WULF', name: 'TeraWulf', sector: 'Technology' },
  
  // --- CANNABIS ---
  { symbol: 'TLRY', name: 'Tilray Brands', sector: 'Healthcare' },
  { symbol: 'CGC', name: 'Canopy Growth', sector: 'Healthcare' },
  { symbol: 'ACB', name: 'Aurora Cannabis', sector: 'Healthcare' },
  { symbol: 'CRON', name: 'Cronos Group', sector: 'Healthcare' },
  { symbol: 'SNDL', name: 'SNDL Inc', sector: 'Consumer Defensive' },
  { symbol: 'OGI', name: 'Organigram', sector: 'Healthcare' },
  { symbol: 'MAPS', name: 'WM Technology', sector: 'Technology' },
  { symbol: 'IIPR', name: 'Innovative Industrial', sector: 'Real Estate' },
  { symbol: 'GRWG', name: 'GrowGeneration', sector: 'Consumer Cyclical' },
  { symbol: 'SMG', name: 'Scotts Miracle-Gro', sector: 'Basic Materials' },
  
  // --- MEME STOCKS & HIGH RETAIL INTEREST ---
  { symbol: 'GME', name: 'GameStop', sector: 'Consumer Cyclical' },
  { symbol: 'AMC', name: 'AMC Entertainment', sector: 'Communication Services' },
  { symbol: 'BB', name: 'BlackBerry', sector: 'Technology' },
  { symbol: 'KOSS', name: 'Koss Corp', sector: 'Consumer Cyclical' },
  { symbol: 'VSCO', name: 'Victoria\'s Secret', sector: 'Consumer Cyclical' },
  { symbol: 'NOK', name: 'Nokia', sector: 'Technology' },
  { symbol: 'FUBO', name: 'FuboTV', sector: 'Communication Services' },
  { symbol: 'PENN', name: 'PENN Entertainment', sector: 'Consumer Cyclical' },
  
  // --- TRAVEL & LEISURE ---
  { symbol: 'CCL', name: 'Carnival Corp', sector: 'Consumer Cyclical' },
  { symbol: 'RCL', name: 'Royal Caribbean', sector: 'Consumer Cyclical' },
  { symbol: 'NCLH', name: 'Norwegian Cruise', sector: 'Consumer Cyclical' },
  { symbol: 'DAL', name: 'Delta Air Lines', sector: 'Industrials' },
  { symbol: 'UAL', name: 'United Airlines', sector: 'Industrials' },
  { symbol: 'AAL', name: 'American Airlines', sector: 'Industrials' },
  { symbol: 'LUV', name: 'Southwest Airlines', sector: 'Industrials' },
  { symbol: 'ALK', name: 'Alaska Air', sector: 'Industrials' },
  { symbol: 'JBLU', name: 'JetBlue', sector: 'Industrials' },
  { symbol: 'SAVE', name: 'Spirit Airlines', sector: 'Industrials' },
  { symbol: 'EXPE', name: 'Expedia', sector: 'Consumer Cyclical' },
  { symbol: 'TRIP', name: 'TripAdvisor', sector: 'Consumer Cyclical' },
  { symbol: 'H', name: 'Hyatt', sector: 'Consumer Cyclical' },
  { symbol: 'WH', name: 'Wyndham', sector: 'Consumer Cyclical' },
  
  // --- CHINA STOCKS (ADRs) ---
  { symbol: 'BABA', name: 'Alibaba', sector: 'Consumer Cyclical' },
  { symbol: 'JD', name: 'JD.com', sector: 'Consumer Cyclical' },
  { symbol: 'PDD', name: 'PDD Holdings', sector: 'Consumer Cyclical' },
  { symbol: 'BIDU', name: 'Baidu', sector: 'Communication Services' },
  { symbol: 'BILI', name: 'Bilibili', sector: 'Communication Services' },
  { symbol: 'IQ', name: 'iQIYI', sector: 'Communication Services' },
  { symbol: 'TME', name: 'Tencent Music', sector: 'Communication Services' },
  { symbol: 'VIPS', name: 'Vipshop', sector: 'Consumer Cyclical' },
  { symbol: 'ZTO', name: 'ZTO Express', sector: 'Industrials' },
  { symbol: 'BEKE', name: 'KE Holdings', sector: 'Real Estate' },
  { symbol: 'YUMC', name: 'Yum China', sector: 'Consumer Cyclical' },
  { symbol: 'HTHT', name: 'H World Group', sector: 'Consumer Cyclical' },
  { symbol: 'TAL', name: 'TAL Education', sector: 'Consumer Defensive' },
  { symbol: 'EDU', name: 'New Oriental', sector: 'Consumer Defensive' },
  { symbol: 'FUTU', name: 'Futu Holdings', sector: 'Financial' },
  
  // --- BROAD MARKET (S&P 500 & Others) ---
  { symbol: 'ADI', name: 'Analog Devices', sector: 'Technology' },
  { symbol: 'ADP', name: 'ADP', sector: 'Industrials' },
  { symbol: 'ADSK', name: 'Autodesk', sector: 'Technology' },
  { symbol: 'AEP', name: 'American Electric', sector: 'Utilities' },
  { symbol: 'AES', name: 'The AES Corp', sector: 'Utilities' },
  { symbol: 'AFL', name: 'Aflac', sector: 'Financial' },
  { symbol: 'AGCO', name: 'AGCO Corp', sector: 'Industrials' },
  { symbol: 'AIG', name: 'AIG', sector: 'Financial' },
  { symbol: 'AIZ', name: 'Assurant', sector: 'Financial' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher', sector: 'Financial' },
  { symbol: 'AKAM', name: 'Akamai', sector: 'Technology' },
  { symbol: 'ALB', name: 'Albemarle', sector: 'Basic Materials' },
  { symbol: 'ALGM', name: 'Allegro MicroSystems', sector: 'Technology' },
  { symbol: 'ALLE', name: 'Allegion', sector: 'Industrials' },
  { symbol: 'ALLY', name: 'Ally Financial', sector: 'Financial' },
  { symbol: 'ALNY', name: 'Alnylam', sector: 'Healthcare' },
  { symbol: 'AMCR', name: 'Amcor', sector: 'Consumer Cyclical' },
  { symbol: 'AME', name: 'AMETEK', sector: 'Industrials' },
  { symbol: 'AMH', name: 'American Homes 4 Rent', sector: 'Real Estate' },
  { symbol: 'AMP', name: 'Ameriprise Financial', sector: 'Financial' },
  { symbol: 'ANET', name: 'Arista Networks', sector: 'Technology' },
  { symbol: 'ANSS', name: 'ANSYS', sector: 'Technology' },
  { symbol: 'AOS', name: 'A.O. Smith', sector: 'Industrials' },
  { symbol: 'APA', name: 'APA Corp', sector: 'Energy' },
  { symbol: 'APD', name: 'Air Products', sector: 'Basic Materials' },
  { symbol: 'APTV', name: 'Aptiv', sector: 'Consumer Cyclical' },
  { symbol: 'ARE', name: 'Alexandria RE', sector: 'Real Estate' },
  { symbol: 'ATO', name: 'Atmos Energy', sector: 'Utilities' },
  { symbol: 'ATR', name: 'AptarGroup', sector: 'Healthcare' },
  { symbol: 'AVB', name: 'AvalonBay', sector: 'Real Estate' },
  { symbol: 'AVY', name: 'Avery Dennison', sector: 'Consumer Cyclical' },
  { symbol: 'AWK', name: 'American Water', sector: 'Utilities' },
  { symbol: 'AXON', name: 'Axon Enterprise', sector: 'Industrials' },
  { symbol: 'B', name: 'Barnes Group', sector: 'Industrials' },
  { symbol: 'BALL', name: 'Ball Corp', sector: 'Consumer Cyclical' },
  { symbol: 'BAX', name: 'Baxter', sector: 'Healthcare' },
  { symbol: 'BBWI', name: 'Bath & Body Works', sector: 'Consumer Cyclical' },
  { symbol: 'BBY', name: 'Best Buy', sector: 'Consumer Cyclical' },
  { symbol: 'BEN', name: 'Franklin Resources', sector: 'Financial' },
  { symbol: 'BG', name: 'Bunge', sector: 'Consumer Defensive' },
  { symbol: 'BIIB', name: 'Biogen', sector: 'Healthcare' },
  { symbol: 'BIO', name: 'Bio-Rad', sector: 'Healthcare' },
  { symbol: 'BK', name: 'BNY Mellon', sector: 'Financial' },
  { symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy' },
  { symbol: 'BOH', name: 'Bank of Hawaii', sector: 'Financial' },
  { symbol: 'BOKF', name: 'BOK Financial', sector: 'Financial' },
  { symbol: 'BORR', name: 'Borr Drilling', sector: 'Energy' },
  { symbol: 'BR', name: 'Broadridge', sector: 'Industrials' },
  { symbol: 'BRO', name: 'Brown & Brown', sector: 'Financial' },
  { symbol: 'BSY', name: 'Bentley Systems', sector: 'Technology' },
  { symbol: 'BWA', name: 'BorgWarner', sector: 'Consumer Cyclical' },
  { symbol: 'BX', name: 'Blackstone', sector: 'Financial' },
  { symbol: 'BXP', name: 'Boston Properties', sector: 'Real Estate' },
  { symbol: 'C', name: 'Citigroup', sector: 'Financial' },
  { symbol: 'CACI', name: 'CACI International', sector: 'Technology' },
  { symbol: 'CAG', name: 'Conagra Brands', sector: 'Consumer Defensive' },
  { symbol: 'CAH', name: 'Cardinal Health', sector: 'Healthcare' },
  { symbol: 'CASY', name: 'Casey\'s General', sector: 'Consumer Defensive' },
  { symbol: 'CBOE', name: 'Cboe Global', sector: 'Financial' },
  { symbol: 'CBRE', name: 'CBRE Group', sector: 'Real Estate' },
  { symbol: 'CCK', name: 'Crown Holdings', sector: 'Consumer Cyclical' },
  { symbol: 'CDW', name: 'CDW Corp', sector: 'Technology' },
  { symbol: 'CE', name: 'Celanese', sector: 'Basic Materials' },
  { symbol: 'CF', name: 'CF Industries', sector: 'Basic Materials' },
  { symbol: 'CFG', name: 'Citizens Financial', sector: 'Financial' },
  { symbol: 'CHD', name: 'Church & Dwight', sector: 'Consumer Defensive' },
  { symbol: 'CHRW', name: 'C.H. Robinson', sector: 'Industrials' },
  { symbol: 'CHTR', name: 'Charter Comm', sector: 'Communication Services' },
  { symbol: 'CINF', name: 'Cincinnati Financial', sector: 'Financial' },
  { symbol: 'CLX', name: 'Clorox', sector: 'Consumer Defensive' },
  { symbol: 'CMA', name: 'Comerica', sector: 'Financial' },
  { symbol: 'CMCSA', name: 'Comcast', sector: 'Communication Services' },
  { symbol: 'CMG', name: 'Chipotle', sector: 'Consumer Cyclical' },
  { symbol: 'CMI', name: 'Cummins', sector: 'Industrials' },
  { symbol: 'CMS', name: 'CMS Energy', sector: 'Utilities' },
  { symbol: 'CNA', name: 'CNA Financial', sector: 'Financial' },
  { symbol: 'CNP', name: 'CenterPoint', sector: 'Utilities' },
  { symbol: 'COF', name: 'Capital One', sector: 'Financial' },
  { symbol: 'COO', name: 'Cooper Companies', sector: 'Healthcare' },
  { symbol: 'CPB', name: 'Campbell Soup', sector: 'Consumer Defensive' },
  { symbol: 'CPT', name: 'Camden Property', sector: 'Real Estate' },
  { symbol: 'CRL', name: 'Charles River', sector: 'Healthcare' },
  { symbol: 'CSL', name: 'Carlisle', sector: 'Industrials' },
  { symbol: 'CTRA', name: 'Coterra Energy', sector: 'Energy' },
  { symbol: 'CTSH', name: 'Cognizant', sector: 'Technology' },
  { symbol: 'CTVA', name: 'Corteva', sector: 'Basic Materials' },
  { symbol: 'CUBE', name: 'CubeSmart', sector: 'Real Estate' },
  { symbol: 'CVI', name: 'CVR Energy', sector: 'Energy' },
  { symbol: 'CZR', name: 'Caesars Ent', sector: 'Consumer Cyclical' },
  { symbol: 'D', name: 'Dominion Energy', sector: 'Utilities' },
  { symbol: 'DAR', name: 'Darling Ingredients', sector: 'Consumer Defensive' },
  { symbol: 'DBX', name: 'Dropbox', sector: 'Technology' },
  { symbol: 'DFS', name: 'Discover Financial', sector: 'Financial' },
  { symbol: 'DG', name: 'Dollar General', sector: 'Consumer Defensive' },
  { symbol: 'DGX', name: 'Quest Diagnostics', sector: 'Healthcare' },
  { symbol: 'DLTR', name: 'Dollar Tree', sector: 'Consumer Defensive' },
  { symbol: 'DOV', name: 'Dover', sector: 'Industrials' },
  { symbol: 'DOW', name: 'Dow Inc', sector: 'Basic Materials' },
  { symbol: 'DPZ', name: 'Domino\'s Pizza', sector: 'Consumer Cyclical' },
  { symbol: 'DRI', name: 'Darden Restaurants', sector: 'Consumer Cyclical' },
  { symbol: 'DTE', name: 'DTE Energy', sector: 'Utilities' },
  { symbol: 'DTM', name: 'DT Midstream', sector: 'Energy' },
  { symbol: 'DVA', name: 'DaVita', sector: 'Healthcare' },
  { symbol: 'DVN', name: 'Devon Energy', sector: 'Energy' },
  { symbol: 'DXC', name: 'DXC Technology', sector: 'Technology' },
  { symbol: 'EA', name: 'Electronic Arts', sector: 'Communication Services' },
  { symbol: 'EBAY', name: 'eBay', sector: 'Consumer Cyclical' },
  { symbol: 'EIX', name: 'Edison International', sector: 'Utilities' },
  { symbol: 'EL', name: 'Estee Lauder', sector: 'Consumer Defensive' },
  { symbol: 'EMN', name: 'Eastman Chemical', sector: 'Basic Materials' },
  { symbol: 'ENB', name: 'Enbridge', sector: 'Energy' },
  { symbol: 'EPD', name: 'Enterprise Products', sector: 'Energy' },
  { symbol: 'EQT', name: 'EQT Corp', sector: 'Energy' },
  { symbol: 'ERIE', name: 'Erie Indemnity', sector: 'Financial' },
  { symbol: 'ES', name: 'Eversource', sector: 'Utilities' },
  { symbol: 'ESS', name: 'Essex Property', sector: 'Real Estate' },
  { symbol: 'ET', name: 'Energy Transfer', sector: 'Energy' },
  { symbol: 'ETR', name: 'Entergy', sector: 'Utilities' },
  { symbol: 'ETSY', name: 'Etsy', sector: 'Consumer Cyclical' },
  { symbol: 'EVR', name: 'Evercore', sector: 'Financial' },
  { symbol: 'EWBC', name: 'East West Bancorp', sector: 'Financial' },
  { symbol: 'EXC', name: 'Exelon', sector: 'Utilities' },
  { symbol: 'EXPD', name: 'Expeditors', sector: 'Industrials' },
  { symbol: 'F', name: 'Ford', sector: 'Consumer Cyclical' },
  { symbol: 'FANG', name: 'Diamondback', sector: 'Energy' },
  { symbol: 'FAST', name: 'Fastenal', sector: 'Industrials' },
  { symbol: 'FCN', name: 'FTI Consulting', sector: 'Industrials' },
  { symbol: 'FDS', name: 'FactSet', sector: 'Financial' },
  { symbol: 'FE', name: 'FirstEnergy', sector: 'Utilities' },
  { symbol: 'FFIV', name: 'F5, Inc.', sector: 'Technology' },
  { symbol: 'FHN', name: 'First Horizon', sector: 'Financial' },
  { symbol: 'FICO', name: 'Fair Isaac', sector: 'Technology' },
  { symbol: 'FIS', name: 'Fidelity National', sector: 'Technology' },
  { symbol: 'FITB', name: 'Fifth Third', sector: 'Financial' },
  { symbol: 'FLO', name: 'Flowers Foods', sector: 'Consumer Defensive' },
  { symbol: 'FLS', name: 'Flowserve', sector: 'Industrials' },
  { symbol: 'FMC', name: 'FMC Corp', sector: 'Basic Materials' },
  { symbol: 'FNB', name: 'F.N.B. Corp', sector: 'Financial' },
  { symbol: 'FNF', name: 'Fidelity National', sector: 'Financial' },
  { symbol: 'FOX', name: 'Fox Corp', sector: 'Communication Services' },
  { symbol: 'FOXA', name: 'Fox Corp A', sector: 'Communication Services' },
  { symbol: 'FRT', name: 'Federal Realty', sector: 'Real Estate' },
  { symbol: 'FTV', name: 'Fortive', sector: 'Technology' },
  { symbol: 'G', name: 'Genpact', sector: 'Technology' },
  { symbol: 'GATX', name: 'GATX Corp', sector: 'Industrials' },
  { symbol: 'GDDY', name: 'GoDaddy', sector: 'Technology' },
  { symbol: 'GEN', name: 'Gen Digital', sector: 'Technology' },
  { symbol: 'GFL', name: 'GFL Environmental', sector: 'Industrials' },
  { symbol: 'GGG', name: 'Graco', sector: 'Industrials' },
  { symbol: 'GHC', name: 'Graham Holdings', sector: 'Consumer Defensive' },
  { symbol: 'GIS', name: 'General Mills', sector: 'Consumer Defensive' },
  { symbol: 'GL', name: 'Globe Life', sector: 'Financial' },
  { symbol: 'GLW', name: 'Corning', sector: 'Technology' },
  { symbol: 'GPC', name: 'Genuine Parts', sector: 'Consumer Cyclical' },
  { symbol: 'GPK', name: 'Graphic Packaging', sector: 'Consumer Cyclical' },
  { symbol: 'GPN', name: 'Global Payments', sector: 'Financial' },
  { symbol: 'GRMN', name: 'Garmin', sector: 'Technology' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Financial' },
  { symbol: 'GWRE', name: 'Guidewire', sector: 'Technology' },
  { symbol: 'GWW', name: 'W.W. Grainger', sector: 'Industrials' },
  { symbol: 'HAL', name: 'Halliburton', sector: 'Energy' },
  { symbol: 'HAS', name: 'Hasbro', sector: 'Consumer Cyclical' },
  { symbol: 'HBAN', name: 'Huntington Bancshares', sector: 'Financial' },
  { symbol: 'HEI', name: 'HEICO', sector: 'Industrials' },
  { symbol: 'HIG', name: 'Hartford', sector: 'Financial' },
  { symbol: 'HII', name: 'Huntington Ingalls', sector: 'Industrials' },
  { symbol: 'HLI', name: 'Houlihan Lokey', sector: 'Financial' },
  { symbol: 'HOLX', name: 'Hologic', sector: 'Healthcare' },
  { symbol: 'HPE', name: 'Hewlett Packard Ent', sector: 'Technology' },
  { symbol: 'HPQ', name: 'HP Inc.', sector: 'Technology' },
  { symbol: 'HRL', name: 'Hormel Foods', sector: 'Consumer Defensive' },
  { symbol: 'HSY', name: 'Hershey', sector: 'Consumer Defensive' },
  { symbol: 'HUBB', name: 'Hubbell', sector: 'Industrials' },
  { symbol: 'HUM', name: 'Humana', sector: 'Healthcare' },
  { symbol: 'HUN', name: 'Huntsman', sector: 'Basic Materials' },
  { symbol: 'HWM', name: 'Howmet', sector: 'Industrials' },
  { symbol: 'IBM', name: 'IBM', sector: 'Technology' },
  { symbol: 'IDXX', name: 'IDEXX Labs', sector: 'Healthcare' },
  { symbol: 'IEX', name: 'IDEX Corp', sector: 'Industrials' },
  { symbol: 'IFF', name: 'Intl Flavors', sector: 'Basic Materials' },
  { symbol: 'ILMN', name: 'Illumina', sector: 'Healthcare' },
  { symbol: 'INCY', name: 'Incyte', sector: 'Healthcare' },
  { symbol: 'INGR', name: 'Ingredion', sector: 'Consumer Defensive' },
  { symbol: 'IP', name: 'Intl Paper', sector: 'Basic Materials' },
  { symbol: 'IPG', name: 'Interpublic', sector: 'Communication Services' },
  { symbol: 'IRM', name: 'Iron Mountain', sector: 'Real Estate' },
  { symbol: 'IR', name: 'Ingersoll Rand', sector: 'Industrials' },
  { symbol: 'ITT', name: 'ITT Inc', sector: 'Industrials' },
  { symbol: 'IVZ', name: 'Invesco', sector: 'Financial' },
  { symbol: 'J', name: 'Jacobs', sector: 'Industrials' },
  { symbol: 'JBHT', name: 'J.B. Hunt', sector: 'Industrials' },
  { symbol: 'JCI', name: 'Johnson Controls', sector: 'Industrials' },
  { symbol: 'JEF', name: 'Jefferies', sector: 'Financial' },
  { symbol: 'JKHY', name: 'Jack Henry', sector: 'Technology' },
  { symbol: 'DELL', name: 'Dell Technologies', sector: 'Technology' },
  { symbol: 'JWN', name: 'Nordstrom', sector: 'Consumer Cyclical' },
  { symbol: 'K', name: 'Kellogg', sector: 'Consumer Defensive' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Financial' },
  { symbol: 'KEYS', name: 'Keysight', sector: 'Technology' },
  { symbol: 'KHC', name: 'Kraft Heinz', sector: 'Consumer Defensive' },
  { symbol: 'KIM', name: 'Kimco', sector: 'Real Estate' },
  { symbol: 'KKR', name: 'KKR & Co', sector: 'Financial' },
  { symbol: 'KMX', name: 'CarMax', sector: 'Consumer Cyclical' },
  { symbol: 'KNF', name: 'Knife River', sector: 'Industrials' },
  { symbol: 'KNX', name: 'Knight-Swift', sector: 'Industrials' },
  { symbol: 'KR', name: 'Kroger', sector: 'Consumer Defensive' },
  { symbol: 'L', name: 'Loews', sector: 'Financial' },
  { symbol: 'LDOS', name: 'Leidos', sector: 'Technology' },
  { symbol: 'LEG', name: 'Leggett & Platt', sector: 'Consumer Cyclical' },
  { symbol: 'LEN', name: 'Lennar', sector: 'Consumer Cyclical' },
  { symbol: 'LECO', name: 'Lincoln Electric', sector: 'Industrials' },
  { symbol: 'LH', name: 'LabCorp', sector: 'Healthcare' },
  { symbol: 'LHX', name: 'L3Harris', sector: 'Industrials' },
  { symbol: 'LIN', name: 'Linde', sector: 'Basic Materials' },
  { symbol: 'LKQ', name: 'LKQ Corp', sector: 'Consumer Cyclical' },
  { symbol: 'LLY', name: 'Eli Lilly', sector: 'Healthcare' },
  { symbol: 'LNC', name: 'Lincoln National', sector: 'Financial' },
  { symbol: 'LNT', name: 'Alliant Energy', sector: 'Utilities' },
  { symbol: 'LOGI', name: 'Logitech', sector: 'Technology' },
  { symbol: 'LPLA', name: 'LPL Financial', sector: 'Financial' },
  { symbol: 'LPX', name: 'Louisiana-Pacific', sector: 'Basic Materials' },
  { symbol: 'LSI', name: 'Life Storage', sector: 'Real Estate' },
  { symbol: 'LSTR', name: 'Landstar', sector: 'Industrials' },
  { symbol: 'LUV', name: 'Southwest', sector: 'Industrials' },
  { symbol: 'LVS', name: 'Las Vegas Sands', sector: 'Consumer Cyclical' },
  { symbol: 'LW', name: 'Lamb Weston', sector: 'Consumer Defensive' },
  { symbol: 'LYB', name: 'LyondellBasell', sector: 'Basic Materials' },
  { symbol: 'LYV', name: 'Live Nation', sector: 'Communication Services' },
  { symbol: 'MAA', name: 'Mid-America Apt', sector: 'Real Estate' },
  { symbol: 'MAN', name: 'ManpowerGroup', sector: 'Industrials' },
  { symbol: 'MAS', name: 'Masco', sector: 'Industrials' },
  { symbol: 'MCD', name: 'McDonald\'s', sector: 'Consumer Cyclical' },
  { symbol: 'MCHP', name: 'Microchip', sector: 'Technology' },
  { symbol: 'MCK', name: 'McKesson', sector: 'Healthcare' },
  { symbol: 'MCO', name: 'Moody\'s', sector: 'Financial' },
  { symbol: 'MDLZ', name: 'Mondelez', sector: 'Consumer Defensive' },
  { symbol: 'MDT', name: 'Medtronic', sector: 'Healthcare' },
  { symbol: 'MDU', name: 'MDU Resources', sector: 'Industrials' },
  { symbol: 'MET', name: 'MetLife', sector: 'Financial' },
  { symbol: 'MGM', name: 'MGM Resorts', sector: 'Consumer Cyclical' },
  { symbol: 'MHK', name: 'Mohawk', sector: 'Consumer Cyclical' },
  { symbol: 'MKC', name: 'McCormick', sector: 'Consumer Defensive' },
  { symbol: 'MKTX', name: 'MarketAxess', sector: 'Financial' },
  { symbol: 'MLM', name: 'Martin Marietta', sector: 'Basic Materials' },
  { symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Financial' },
  { symbol: 'MMM', name: '3M', sector: 'Industrials' },
  { symbol: 'MOH', name: 'Molina', sector: 'Healthcare' },
  { symbol: 'MOS', name: 'Mosaic', sector: 'Basic Materials' },
  { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy' },
  { symbol: 'MPW', name: 'Medical Properties', sector: 'Real Estate' },
  { symbol: 'MPWR', name: 'Monolithic Power', sector: 'Technology' },
  { symbol: 'MRK', name: 'Merck', sector: 'Healthcare' },
  { symbol: 'MRO', name: 'Marathon Oil', sector: 'Energy' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financial' },
  { symbol: 'MSCI', name: 'MSCI Inc', sector: 'Financial' },
  { symbol: 'MSI', name: 'Motorola', sector: 'Technology' },
  { symbol: 'MTB', name: 'M&T Bank', sector: 'Financial' },
  { symbol: 'MTCH', name: 'Match Group', sector: 'Technology' },
  { symbol: 'MTD', name: 'Mettler-Toledo', sector: 'Healthcare' },
  { symbol: 'MU', name: 'Micron', sector: 'Technology' },
  { symbol: 'NDAQ', name: 'Nasdaq Inc', sector: 'Financial' },
  { symbol: 'NDSN', name: 'Nordson', sector: 'Industrials' },
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { symbol: 'NEM', name: 'Newmont', sector: 'Basic Materials' },
  { symbol: 'NFG', name: 'National Fuel', sector: 'Utilities' },
  { symbol: 'NI', name: 'NiSource', sector: 'Utilities' },
  { symbol: 'NKE', name: 'Nike', sector: 'Consumer Cyclical' },
  { symbol: 'GEV', name: 'GE Vernova', sector: 'Industrials' },
  { symbol: 'NLY', name: 'Annaly', sector: 'Real Estate' },
  { symbol: 'NNN', name: 'National Retail', sector: 'Real Estate' },
  { symbol: 'NOC', name: 'Northrop Grumman', sector: 'Industrials' },
  { symbol: 'NOV', name: 'NOV Inc', sector: 'Energy' },
  { symbol: 'NRG', name: 'NRG Energy', sector: 'Utilities' },
  { symbol: 'NSC', name: 'Norfolk Southern', sector: 'Industrials' },
  { symbol: 'NTAP', name: 'NetApp', sector: 'Technology' },
  { symbol: 'NTRS', name: 'Northern Trust', sector: 'Financial' },
  { symbol: 'NUE', name: 'Nucor', sector: 'Basic Materials' },
  { symbol: 'NVT', name: 'nVent', sector: 'Industrials' },
  { symbol: 'NVR', name: 'NVR Inc', sector: 'Consumer Cyclical' },
  { symbol: 'NWL', name: 'Newell Brands', sector: 'Consumer Cyclical' },
  { symbol: 'NWS', name: 'News Corp', sector: 'Communication Services' },
  { symbol: 'NXST', name: 'Nexstar', sector: 'Communication Services' },
  { symbol: 'O', name: 'Realty Income', sector: 'Real Estate' },
  { symbol: 'OC', name: 'Owens Corning', sector: 'Industrials' },
  { symbol: 'ODFL', name: 'Old Dominion', sector: 'Industrials' },
  { symbol: 'OGE', name: 'OGE Energy', sector: 'Utilities' },
  { symbol: 'OHI', name: 'Omega Healthcare', sector: 'Real Estate' },
  { symbol: 'OI', name: 'O-I Glass', sector: 'Consumer Cyclical' },
  { symbol: 'OKE', name: 'ONEOK', sector: 'Energy' },
  { symbol: 'OLN', name: 'Olin', sector: 'Basic Materials' },
  { symbol: 'OMC', name: 'Omnicom', sector: 'Communication Services' },
  { symbol: 'ON', name: 'ON Semi', sector: 'Technology' },
  { symbol: 'ORCL', name: 'Oracle', sector: 'Technology' },
  { symbol: 'ORLY', name: 'O\'Reilly', sector: 'Consumer Cyclical' },
  { symbol: 'OSK', name: 'Oshkosh', sector: 'Industrials' },
  { symbol: 'OTIS', name: 'Otis', sector: 'Industrials' },
  { symbol: 'OVV', name: 'Ovintiv', sector: 'Energy' },
  { symbol: 'OXY', name: 'Occidental', sector: 'Energy' },
  { symbol: 'PAYC', name: 'Paycom', sector: 'Technology' },
  { symbol: 'PAYX', name: 'Paychex', sector: 'Industrials' },
  { symbol: 'PCAR', name: 'PACCAR', sector: 'Industrials' },
  { symbol: 'PCG', name: 'PG&E', sector: 'Utilities' },
  { symbol: 'DOC', name: 'Healthpeak Properties', sector: 'Real Estate' },
  { symbol: 'PEG', name: 'Public Service', sector: 'Utilities' },
  { symbol: 'PEN', name: 'Penumbra', sector: 'Healthcare' },
  { symbol: 'PEP', name: 'PepsiCo', sector: 'Consumer Defensive' },
  { symbol: 'PFE', name: 'Pfizer', sector: 'Healthcare' },
  { symbol: 'PFG', name: 'Principal Financial', sector: 'Financial' },
  { symbol: 'PG', name: 'P&G', sector: 'Consumer Defensive' },
  { symbol: 'PGR', name: 'Progressive', sector: 'Financial' },
  { symbol: 'PH', name: 'Parker-Hannifin', sector: 'Industrials' },
  { symbol: 'PHM', name: 'PulteGroup', sector: 'Consumer Cyclical' },
  { symbol: 'PI', name: 'Impinj', sector: 'Technology' },
  { symbol: 'PKG', name: 'Packaging Corp', sector: 'Consumer Cyclical' },
  { symbol: 'PLD', name: 'Prologis', sector: 'Real Estate' },
  { symbol: 'PM', name: 'Philip Morris', sector: 'Consumer Defensive' },
  { symbol: 'PNC', name: 'PNC', sector: 'Financial' },
  { symbol: 'PNR', name: 'Pentair', sector: 'Industrials' },
  { symbol: 'PNW', name: 'Pinnacle West', sector: 'Utilities' },
  { symbol: 'POOL', name: 'Pool Corp', sector: 'Consumer Cyclical' },
  { symbol: 'POR', name: 'Portland General', sector: 'Utilities' },
  { symbol: 'POST', name: 'Post Holdings', sector: 'Consumer Defensive' },
  { symbol: 'PPG', name: 'PPG Industries', sector: 'Basic Materials' },
  { symbol: 'PPL', name: 'PPL Corp', sector: 'Utilities' },
  { symbol: 'PRU', name: 'Prudential', sector: 'Financial' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy' },
  { symbol: 'PTC', name: 'PTC Inc', sector: 'Technology' },
  { symbol: 'PWR', name: 'Quanta Services', sector: 'Industrials' },
  { symbol: 'QCOM', name: 'Qualcomm', sector: 'Technology' },
  { symbol: 'QRVO', name: 'Qorvo', sector: 'Technology' },
  { symbol: 'R', name: 'Ryder', sector: 'Industrials' },
  { symbol: 'RCL', name: 'Royal Caribbean', sector: 'Consumer Cyclical' },
  { symbol: 'REG', name: 'Regency Centers', sector: 'Real Estate' },
  { symbol: 'REGN', name: 'Regeneron', sector: 'Healthcare' },
  { symbol: 'RF', name: 'Regions Financial', sector: 'Financial' },
  { symbol: 'RHI', name: 'Robert Half', sector: 'Industrials' },
  { symbol: 'RJF', name: 'Raymond James', sector: 'Financial' },
  { symbol: 'RL', name: 'Ralph Lauren', sector: 'Consumer Cyclical' },
  { symbol: 'RMD', name: 'ResMed', sector: 'Healthcare' },
  { symbol: 'ROK', name: 'Rockwell Automation', sector: 'Industrials' },
  { symbol: 'ROL', name: 'Rollins', sector: 'Consumer Cyclical' },
  { symbol: 'ROP', name: 'Roper', sector: 'Technology' },
  { symbol: 'ROST', name: 'Ross Stores', sector: 'Consumer Cyclical' },
  { symbol: 'RPM', name: 'RPM International', sector: 'Basic Materials' },
  { symbol: 'RS', name: 'Reliance Steel', sector: 'Basic Materials' },
  { symbol: 'RSG', name: 'Republic Services', sector: 'Industrials' },
  { symbol: 'RTX', name: 'Raytheon', sector: 'Industrials' },
  { symbol: 'RYAAY', name: 'Ryanair', sector: 'Industrials' },
  { symbol: 'SBAC', name: 'SBA Comm', sector: 'Real Estate' },
  { symbol: 'SBUX', name: 'Starbucks', sector: 'Consumer Cyclical' },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Financial' },
  { symbol: 'SCI', name: 'Service Corp', sector: 'Consumer Cyclical' },
  { symbol: 'SEE', name: 'Sealed Air', sector: 'Consumer Cyclical' },
  { symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Basic Materials' },
  { symbol: 'SJM', name: 'Smucker', sector: 'Consumer Defensive' },
  { symbol: 'SLB', name: 'Schlumberger', sector: 'Energy' },
  { symbol: 'SLG', name: 'SL Green', sector: 'Real Estate' },
  { symbol: 'SNA', name: 'Snap-on', sector: 'Industrials' },
  { symbol: 'SNPS', name: 'Synopsys', sector: 'Technology' },
  { symbol: 'SO', name: 'Southern Co', sector: 'Utilities' },
  { symbol: 'SPG', name: 'Simon Property', sector: 'Real Estate' },
  { symbol: 'SPGI', name: 'S&P Global', sector: 'Financial' },
  { symbol: 'SPLK', name: 'Splunk', sector: 'Technology' },
  { symbol: 'SPR', name: 'Spirit AeroSystems', sector: 'Industrials' },
  { symbol: 'SQ', name: 'Block', sector: 'Financial' },
  { symbol: 'SRE', name: 'Sempra', sector: 'Utilities' },
  { symbol: 'STE', name: 'STERIS', sector: 'Healthcare' },
  { symbol: 'STT', name: 'State Street', sector: 'Financial' },
  { symbol: 'STX', name: 'Seagate', sector: 'Technology' },
  { symbol: 'STZ', name: 'Constellation', sector: 'Consumer Defensive' },
  { symbol: 'SWK', name: 'Stanley Black & Decker', sector: 'Industrials' },
  { symbol: 'SWKS', name: 'Skyworks', sector: 'Technology' },
  { symbol: 'SYF', name: 'Synchrony', sector: 'Financial' },
  { symbol: 'SYK', name: 'Stryker', sector: 'Healthcare' },
  { symbol: 'SYY', name: 'Sysco', sector: 'Consumer Defensive' },
  { symbol: 'T', name: 'AT&T', sector: 'Communication Services' },
  { symbol: 'TAP', name: 'Molson Coors', sector: 'Consumer Defensive' },
  { symbol: 'TDG', name: 'TransDigm', sector: 'Industrials' },
  { symbol: 'TDY', name: 'Teledyne', sector: 'Technology' },
  { symbol: 'TECH', name: 'Bio-Techne', sector: 'Healthcare' },
  { symbol: 'TEL', name: 'TE Connectivity', sector: 'Technology' },
  { symbol: 'TER', name: 'Teradyne', sector: 'Technology' },
  { symbol: 'TFC', name: 'Truist', sector: 'Financial' },
  { symbol: 'TFX', name: 'Teleflex', sector: 'Healthcare' },
  { symbol: 'TGT', name: 'Target', sector: 'Consumer Defensive' },
  { symbol: 'THC', name: 'Tenet Healthcare', sector: 'Healthcare' },
  { symbol: 'TJX', name: 'TJX Cos', sector: 'Consumer Cyclical' },
  { symbol: 'TMO', name: 'Thermo Fisher', sector: 'Healthcare' },
  { symbol: 'TMUS', name: 'T-Mobile', sector: 'Communication Services' },
  { symbol: 'TOL', name: 'Toll Brothers', sector: 'Consumer Cyclical' },
  { symbol: 'TPR', name: 'Tapestry', sector: 'Consumer Cyclical' },
  { symbol: 'TRMB', name: 'Trimble', sector: 'Technology' },
  { symbol: 'TROW', name: 'T. Rowe Price', sector: 'Financial' },
  { symbol: 'TRV', name: 'Travelers', sector: 'Financial' },
  { symbol: 'TSCO', name: 'Tractor Supply', sector: 'Consumer Cyclical' },
  { symbol: 'TSN', name: 'Tyson Foods', sector: 'Consumer Defensive' },
  { symbol: 'TT', name: 'Trane', sector: 'Industrials' },
  { symbol: 'TTWO', name: 'Take-Two', sector: 'Communication Services' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
  { symbol: 'TXT', name: 'Textron', sector: 'Industrials' },
  { symbol: 'TYL', name: 'Tyler Tech', sector: 'Technology' },
  { symbol: 'UA', name: 'Under Armour', sector: 'Consumer Cyclical' },
  { symbol: 'UAA', name: 'Under Armour', sector: 'Consumer Cyclical' },
  { symbol: 'UAL', name: 'United Airlines', sector: 'Industrials' },
  { symbol: 'UDR', name: 'UDR Inc', sector: 'Real Estate' },
  { symbol: 'UHS', name: 'Universal Health', sector: 'Healthcare' },
  { symbol: 'ULTA', name: 'Ulta Beauty', sector: 'Consumer Cyclical' },
  { symbol: 'UNH', name: 'UnitedHealth', sector: 'Healthcare' },
  { symbol: 'UNP', name: 'Union Pacific', sector: 'Industrials' },
  { symbol: 'UPS', name: 'UPS', sector: 'Industrials' },
  { symbol: 'URI', name: 'United Rentals', sector: 'Industrials' },
  { symbol: 'USB', name: 'US Bancorp', sector: 'Financial' },
  { symbol: 'V', name: 'Visa', sector: 'Financial' },
  { symbol: 'VFC', name: 'VF Corp', sector: 'Consumer Cyclical' },
  { symbol: 'VICI', name: 'VICI Properties', sector: 'Real Estate' },
  { symbol: 'VLO', name: 'Valero', sector: 'Energy' },
  { symbol: 'VMC', name: 'Vulcan Materials', sector: 'Basic Materials' },
  { symbol: 'VNO', name: 'Vornado', sector: 'Real Estate' },
  { symbol: 'VRSK', name: 'Verisk', sector: 'Industrials' },
  { symbol: 'VRSN', name: 'VeriSign', sector: 'Technology' },
  { symbol: 'VRTX', name: 'Vertex', sector: 'Healthcare' },
  { symbol: 'VTR', name: 'Ventas', sector: 'Real Estate' },
  { symbol: 'VZ', name: 'Verizon', sector: 'Communication Services' },
  { symbol: 'WAB', name: 'Wabtec', sector: 'Industrials' },
  { symbol: 'WAT', name: 'Waters', sector: 'Healthcare' },
  { symbol: 'WBA', name: 'Walgreens', sector: 'Healthcare' },
  { symbol: 'WDC', name: 'Western Digital', sector: 'Technology' },
  { symbol: 'WEC', name: 'WEC Energy', sector: 'Utilities' },
  { symbol: 'WELL', name: 'Welltower', sector: 'Real Estate' },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Financial' },
  { symbol: 'WHR', name: 'Whirlpool', sector: 'Consumer Cyclical' },
  { symbol: 'WM', name: 'Waste Management', sector: 'Industrials' },
  { symbol: 'WMB', name: 'Williams Cos', sector: 'Energy' },
  { symbol: 'WMT', name: 'Walmart', sector: 'Consumer Defensive' },
  { symbol: 'WRB', name: 'W.R. Berkley', sector: 'Financial' },
  { symbol: 'WRK', name: 'WestRock', sector: 'Consumer Cyclical' },
  { symbol: 'WST', name: 'West Pharma', sector: 'Healthcare' },
  { symbol: 'WU', name: 'Western Union', sector: 'Financial' },
  { symbol: 'WY', name: 'Weyerhaeuser', sector: 'Real Estate' },
  { symbol: 'WYNN', name: 'Wynn Resorts', sector: 'Consumer Cyclical' },
  { symbol: 'XEL', name: 'Xcel Energy', sector: 'Utilities' },
  { symbol: 'MRVL', name: 'Marvell Tech', sector: 'Technology' },
  { symbol: 'XOM', name: 'Exxon Mobil', sector: 'Energy' },
  { symbol: 'XRAY', name: 'Dentsply Sirona', sector: 'Healthcare' },
  { symbol: 'XRX', name: 'Xerox', sector: 'Technology' },
  { symbol: 'XYL', name: 'Xylem', sector: 'Industrials' },
  { symbol: 'YUM', name: 'Yum! Brands', sector: 'Consumer Cyclical' },
  { symbol: 'ZBH', name: 'Zimmer Biomet', sector: 'Healthcare' },
  { symbol: 'ZBRA', name: 'Zebra Tech', sector: 'Technology' },
  { symbol: 'ZION', name: 'Zions Bancorp', sector: 'Financial' },
  { symbol: 'ZTS', name: 'Zoetis', sector: 'Healthcare' },
  
  // --- ETFS: INDEX & SECTOR ---
  { symbol: 'SPY', name: 'S&P 500 ETF', sector: 'ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500', sector: 'ETF' },
  { symbol: 'IVV', name: 'iShares Core S&P 500', sector: 'ETF' },
  { symbol: 'QQQ', name: 'Invesco QQQ', sector: 'ETF' },
  { symbol: 'TQQQ', name: 'ProShares UltraPro QQQ', sector: 'ETF' },
  { symbol: 'SQQQ', name: 'ProShares UltraPro Short QQQ', sector: 'ETF' },
  { symbol: 'DIA', name: 'Dow Jones ETF', sector: 'ETF' },
  { symbol: 'IWM', name: 'Russell 2000 ETF', sector: 'ETF' },
  { symbol: 'VTI', name: 'Vanguard Total Stock', sector: 'ETF' },
  { symbol: 'VEA', name: 'Vanguard Developed Markets', sector: 'ETF' },
  { symbol: 'VWO', name: 'Vanguard Emerging Markets', sector: 'ETF' },
  { symbol: 'EEM', name: 'iShares Emerging Markets', sector: 'ETF' },
  { symbol: 'EFA', name: 'iShares EAFE', sector: 'ETF' },
  { symbol: 'XLE', name: 'Energy Select Sector', sector: 'ETF' },
  { symbol: 'XLF', name: 'Financial Select Sector', sector: 'ETF' },
  { symbol: 'XLK', name: 'Technology Select Sector', sector: 'ETF' },
  { symbol: 'XLV', name: 'Health Care Select Sector', sector: 'ETF' },
  { symbol: 'XLY', name: 'Consumer Discretionary', sector: 'ETF' },
  { symbol: 'XLP', name: 'Consumer Staples', sector: 'ETF' },
  { symbol: 'XLI', name: 'Industrial Select Sector', sector: 'ETF' },
  { symbol: 'XLU', name: 'Utilities Select Sector', sector: 'ETF' },
  { symbol: 'XLB', name: 'Materials Select Sector', sector: 'ETF' },
  { symbol: 'XLC', name: 'Communication Services', sector: 'ETF' },
  { symbol: 'XLRE', name: 'Real Estate Select Sector', sector: 'ETF' },
  { symbol: 'SMH', name: 'VanEck Semiconductor', sector: 'ETF' },
  { symbol: 'SOXX', name: 'iShares Semiconductor', sector: 'ETF' },
  { symbol: 'SOXL', name: 'Direxion Daily Semi Bull', sector: 'ETF' },
  { symbol: 'SOXS', name: 'Direxion Daily Semi Bear', sector: 'ETF' },
  { symbol: 'IBB', name: 'iShares Biotechnology', sector: 'ETF' },
  { symbol: 'XBI', name: 'SPDR Biotech', sector: 'ETF' },
  { symbol: 'LABU', name: 'Direxion Biotech Bull', sector: 'ETF' },
  { symbol: 'LABD', name: 'Direxion Biotech Bear', sector: 'ETF' },
  { symbol: 'ITB', name: 'iShares Home Construction', sector: 'ETF' },
  { symbol: 'XHB', name: 'SPDR Homebuilders', sector: 'ETF' },
  { symbol: 'JETS', name: 'US Global Jets', sector: 'ETF' },
  { symbol: 'KRE', name: 'SPDR Regional Banking', sector: 'ETF' },
  { symbol: 'KBE', name: 'SPDR Bank ETF', sector: 'ETF' },
  { symbol: 'GDX', name: 'VanEck Gold Miners', sector: 'ETF' },
  { symbol: 'GDXJ', name: 'VanEck Junior Gold Miners', sector: 'ETF' },
  { symbol: 'SIL', name: 'Global X Silver Miners', sector: 'ETF' },
  { symbol: 'SILJ', name: 'Prime Junior Silver Miners', sector: 'ETF' },
  { symbol: 'URA', name: 'Global X Uranium', sector: 'ETF' },
  { symbol: 'URNM', name: 'Sprott Uranium Miners', sector: 'ETF' },
  { symbol: 'TAN', name: 'Invesco Solar', sector: 'ETF' },
  { symbol: 'ICLN', name: 'iShares Clean Energy', sector: 'ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation', sector: 'ETF' },
  { symbol: 'ARKG', name: 'ARK Genomic', sector: 'ETF' },
  { symbol: 'ARKW', name: 'ARK Next Gen Internet', sector: 'ETF' },
  { symbol: 'ARKF', name: 'ARK Fintech', sector: 'ETF' },
  { symbol: 'ARKQ', name: 'ARK Autonomous Tech', sector: 'ETF' },
  { symbol: 'ARKX', name: 'ARK Space Exploration', sector: 'ETF' },
  { symbol: 'BITO', name: 'ProShares Bitcoin Strategy', sector: 'ETF' },
  { symbol: 'GBTC', name: 'Grayscale Bitcoin Trust', sector: 'ETF' },
  { symbol: 'IBIT', name: 'iShares Bitcoin Trust', sector: 'ETF' },
  { symbol: 'FBTC', name: 'Fidelity Wise Origin Bitcoin', sector: 'ETF' },
  { symbol: 'ARKB', name: 'ARK 21Shares Bitcoin', sector: 'ETF' },
  { symbol: 'BITB', name: 'Bitwise Bitcoin', sector: 'ETF' },
  { symbol: 'HODL', name: 'VanEck Bitcoin Trust', sector: 'ETF' },
  { symbol: 'BRRR', name: 'Valkyrie Bitcoin Fund', sector: 'ETF' },
  { symbol: 'EZBC', name: 'Franklin Bitcoin ETF', sector: 'ETF' },
  { symbol: 'BTCW', name: 'WisdomTree Bitcoin Fund', sector: 'ETF' },
  { symbol: 'GLD', name: 'SPDR Gold Shares', sector: 'ETF' },
  { symbol: 'IAU', name: 'iShares Gold Trust', sector: 'ETF' },
  { symbol: 'SLV', name: 'iShares Silver Trust', sector: 'ETF' },
  { symbol: 'USO', name: 'United States Oil Fund', sector: 'ETF' },
  { symbol: 'UNG', name: 'United States Natural Gas', sector: 'ETF' },
  { symbol: 'DBC', name: 'Invesco DB Commodity', sector: 'ETF' },
  { symbol: 'GSG', name: 'iShares GSCI Commodity', sector: 'ETF' },
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury', sector: 'ETF' },
  { symbol: 'TMF', name: 'Direxion Daily 20+ Yr Bull', sector: 'ETF' },
  { symbol: 'TMV', name: 'Direxion Daily 20+ Yr Bear', sector: 'ETF' },
  { symbol: 'IEF', name: 'iShares 7-10 Year Treasury', sector: 'ETF' },
  { symbol: 'SHY', name: 'iShares 1-3 Year Treasury', sector: 'ETF' },
  { symbol: 'BIL', name: 'SPDR 1-3 Month T-Bill', sector: 'ETF' },
  { symbol: 'SGOV', name: 'iShares 0-3 Month Treasury', sector: 'ETF' },
  { symbol: 'LQD', name: 'iShares Inv Grade Corp Bond', sector: 'ETF' },
  { symbol: 'HYG', name: 'iShares High Yield Corp Bond', sector: 'ETF' },
  { symbol: 'JNK', name: 'SPDR Bloomberg High Yield', sector: 'ETF' },
  { symbol: 'MUB', name: 'iShares National Muni Bond', sector: 'ETF' },
  { symbol: 'TIP', name: 'iShares TIPS Bond', sector: 'ETF' },
  { symbol: 'BND', name: 'Vanguard Total Bond Market', sector: 'ETF' },
  { symbol: 'AGG', name: 'iShares Core US Aggregate', sector: 'ETF' },
  { symbol: 'VIXY', name: 'ProShares VIX Short-Term', sector: 'ETF' },
  { symbol: 'UVXY', name: 'ProShares Ultra VIX', sector: 'ETF' },
  { symbol: 'SVXY', name: 'ProShares Short VIX', sector: 'ETF' }
];
